CREATE TABLE "IPMS_DATA"."MAINGROUP" 
("CODE" NVARCHAR2(20) NOT NULL ENABLE, 
"TOPGROUP_CODE" NVARCHAR2(20),
"NAME" NVARCHAR2(200) NOT NULL ENABLE, 
"IS_ACTIVE" number(1,0), 
"MODIFY_DATE" date default sysdate,
CONSTRAINT "MAINGROUP_PK" PRIMARY KEY ("CODE"),
FOREIGN KEY ("TOPGROUP_CODE") REFERENCES "IPMS_DATA"."TOPGROUP" ("CODE") ON DELETE CASCADE ENABLE);