CREATE TABLE "IPMS_DATA"."IMPORT_BU" 
("IMPORT_ID" NVARCHAR2(20) NOT NULL ENABLE, 
"CODE" NVARCHAR2(20) NOT NULL ENABLE, 
"NAME" NVARCHAR2(200) NOT NULL ENABLE, 
"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
"STATUS_CODE" NVARCHAR2(10) DEFAULT 'NEW' NOT NULL ENABLE, 
"STATUS_DESCRIPTION" NVARCHAR2(500), 
"CREATE_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
check (is_active in (0,1)) enable, 
PRIMARY KEY ("IMPORT_ID", "CODE"),
FOREIGN KEY ("IMPORT_ID")
REFERENCES "IPMS_DATA"."IMPORT" ("ID") ON DELETE CASCADE ENABLE, 
FOREIGN KEY ("STATUS_CODE")
REFERENCES "IPMS_DATA"."IMPORT_STATUS" ("CODE") ENABLE);