--------------------------------------------------------
--  File created - Monday-February-07-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COLLABORATION_DETAILS
--------------------------------------------------------
CREATE SEQUENCE  IPMS_DATA.COLLABORATION_ID_SEQ  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  CYCLE  NOKEEP  GLOBAL ;

  CREATE TABLE IPMS_DATA.COLLABORATION_DETAILS 
   (	ID NUMBER(10,0), 
	PROJECT_ID NVARCHAR2(20), 
	CREATE_USER_ID NVARCHAR2(20), 
	UPDATE_USER_ID NVARCHAR2(20), 
	CREATE_DATE DATE DEFAULT SYSDATE, 
	UPDATE_DATE DATE DEFAULT SYSDATE, 
	PARTNER NVARCHAR2(100), 
	COLLABORATION_TYPE NVARCHAR2(100), 
	START_PHASE NVARCHAR2(100), 
	END_PHASE NVARCHAR2(100), 
	COMMENT NVARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
  GRANT SELECT ON IPMS_DATA.COLLABORATION_DETAILS TO MXCBI;
  GRANT SELECT ON IPMS_DATA.COLLABORATION_DETAILS TO IPMS_REPO;
--------------------------------------------------------
--  DDL for Index SYS_C00266651
--------------------------------------------------------

  CREATE UNIQUE INDEX IPMS_DATA.SYS_C00266651 ON IPMS_DATA.COLLABORATION_DETAILS (ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;

--------------------------------------------------------
--  Constraints for Table COLLABORATION_DETAILS
--------------------------------------------------------

  ALTER TABLE IPMS_DATA.COLLABORATION_DETAILS MODIFY (ID NOT NULL ENABLE);
  ALTER TABLE IPMS_DATA.COLLABORATION_DETAILS ADD PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE;
