
  CREATE TABLE "IPMS_DATA"."IMPORT_D2" 
   (	"IMPORT_ID" NVARCHAR2(20) NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_NAME" NVARCHAR2(100), 
	"PROJECT_PHASE_NO" NUMBER, 
	"PROJECT_PHASE" NVARCHAR2(250), 
	"TRG_CODE" NVARCHAR2(256), 
	"TRG" NVARCHAR2(250), 
	"ER" NVARCHAR2(250), 
	"TARGET_GENE_CODE" NVARCHAR2(250), 
	"D2_COMPOUND" NVARCHAR2(80), 
	"START_HTS_DATE" DATE, 
	"GENERAL_PROJECT_FRAME" NVARCHAR2(250), 
	"STATUS" NVARCHAR2(10), 
	"MODIFIER" NVARCHAR2(32), 
	"MODIFY_DATE" DATE, 
	"ISNEW" NVARCHAR2(1), 
	"STATUS_CODE" NVARCHAR2(10) DEFAULT 'NEW' NOT NULL ENABLE, 
	"STATUS_DESCRIPTION" NVARCHAR2(500), 
	"CREATE_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"UPDATE_DATE" DATE, 
	 PRIMARY KEY ("PROJECT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" FLASHBACK ARCHIVE "FDA_IMPORT";