--------------------------------------------------------
--  DDL for Table PARTNER
------------------------------------------------------

  CREATE TABLE IPMS_DATA.PARTNER 
   (	CODE NVARCHAR2(10), 
	NAME NVARCHAR2(100), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	DESCRIPTION NVARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
  GRANT SELECT ON IPMS_DATA.PARTNER TO IPMS_REPO;
--------------------------------------------------------
--  DDL for Index SYS_C00295530
--------------------------------------------------------

  CREATE UNIQUE INDEX IPMS_DATA.SYS_C00295530 ON IPMS_DATA.PARTNER (CODE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
--------------------------------------------------------
--  Constraints for Table PARTNER
--------------------------------------------------------

  ALTER TABLE IPMS_DATA.PARTNER MODIFY (CODE NOT NULL ENABLE);
  ALTER TABLE IPMS_DATA.PARTNER MODIFY (NAME NOT NULL ENABLE);
  ALTER TABLE IPMS_DATA.PARTNER MODIFY (IS_ACTIVE NOT NULL ENABLE);
  ALTER TABLE IPMS_DATA.PARTNER ADD CHECK (is_active in (0,1)) ENABLE;
  ALTER TABLE IPMS_DATA.PARTNER ADD PRIMARY KEY (CODE)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE;
