--------------------------------------------------------
--  File created - Monday-February-07-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROJECT_RELATED_MSP
--------------------------------------------------------
CREATE SEQUENCE  IPMS_DATA.PRJ_REL_MSP_ID_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  CYCLE  NOKEEP  GLOBAL ;

  CREATE TABLE IPMS_DATA.PROJECT_RELATED_MSP 
   (	ID NUMBER, 
	PROJECT_ID NVARCHAR2(20), 
	REL_MSP_PROJECT_ID VARCHAR2(30 BYTE), 
	CREATE_DATE DATE, 
	CREATE_USER_ID VARCHAR2(20 BYTE), 
	UPDATE_DATE DATE, 
	UPDATE_USER_ID VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
  GRANT SELECT ON IPMS_DATA.PROJECT_RELATED_MSP TO IPMS_REPO;
--------------------------------------------------------
--  DDL for Index PRJ_REL_MSP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX IPMS_DATA.PRJ_REL_MSP_PK ON IPMS_DATA.PROJECT_RELATED_MSP (ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PRJ_REL_MSP_PROJECT_CODE_FKI
--------------------------------------------------------

  CREATE INDEX IPMS_DATA.PRJ_REL_MSP_PROJECT_CODE_FKI ON IPMS_DATA.PROJECT_RELATED_MSP (PROJECT_CODE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;

--------------------------------------------------------
--  Constraints for Table PROJECT_RELATED_MSP
--------------------------------------------------------

  ALTER TABLE IPMS_DATA.PROJECT_RELATED_MSP MODIFY (PROJECT_CODE NOT NULL ENABLE);
  ALTER TABLE IPMS_DATA.PROJECT_RELATED_MSP MODIFY (REL_MSP_PROJECT_ID CONSTRAINT PRJ_REL_MSP_ID_CNN NOT NULL ENABLE);
  ALTER TABLE IPMS_DATA.PROJECT_RELATED_MSP MODIFY (CREATE_DATE CONSTRAINT PRJ_REL_MSP_CREATE_DATE_CNN NOT NULL ENABLE);
  ALTER TABLE IPMS_DATA.PROJECT_RELATED_MSP MODIFY (CREATE_USER_ID CONSTRAINT PRJ_MSP_CREATE_BY_CNN NOT NULL ENABLE);
  ALTER TABLE IPMS_DATA.PROJECT_RELATED_MSP MODIFY (UPDATE_DATE CONSTRAINT PRJ_REL_MSP_UPDATE_DATE_CNN NOT NULL ENABLE);
  ALTER TABLE IPMS_DATA.PROJECT_RELATED_MSP MODIFY (UPDATE_USER_ID CONSTRAINT PRJ_REL_MSP_UPDATE_BY_CNN NOT NULL ENABLE);
  ALTER TABLE IPMS_DATA.PROJECT_RELATED_MSP ADD CONSTRAINT PRJ_REL_MSP_PK PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE;
