
  CREATE TABLE "IPMS_DATA"."PROJECT_RELATED_PREDECESSOR" 
   (	"ID" NUMBER, 
	"PROJECT_ID" NVARCHAR2(20) NOT NULL ENABLE, 
	"REL_PREDECESSOR_PROJECT_ID" VARCHAR2(30 BYTE) CONSTRAINT "PRJ_REL_PRED_CODE_CNN" NOT NULL ENABLE, 
	"CREATE_DATE" DATE CONSTRAINT "PRJ_REL_PRED_CREATE_DATE_CNN" NOT NULL ENABLE, 
	"CREATE_USER_ID" VARCHAR2(20 BYTE) CONSTRAINT "PRJ_PRED_CREATE_BY_CNN" NOT NULL ENABLE, 
	"UPDATE_DATE" DATE CONSTRAINT "PRJ_REL_PRED_UPDATE_DATE_CNN" NOT NULL ENABLE, 
	"UPDATE_USER_ID" VARCHAR2(20 BYTE) CONSTRAINT "PRJ_REL_PRED_UPDATE_BY_CNN" NOT NULL ENABLE, 
	 CONSTRAINT "PRJ_REL_PRED_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PRJ_REL_PRED_PROJECT_ID_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "IPMS_DATA"."PROJECT" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE INDEX "IPMS_DATA"."PRJ_REL_PRED_PROJECT_ID_FKI" ON "IPMS_DATA"."PROJECT_RELATED_PREDECESSOR" ("PROJECT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT SELECT ON "IPMS_DATA"."PROJECT_RELATED_PREDECESSOR" TO "IPMS_REPO";
