package com.bayer.ipms.model.views.estimates.common;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 16 11:53:15 EEST 2015
// ---------------------------------------------------------------------
public interface LatestEstimatesTagViewRow extends Row {
    String getId();

    void setIsFrozen(Boolean value);

    void doMeetingAllowedRecalc();

    void refresh();

    Integer getYear();

    String getName();


    String getPreviousLetId();

    RowIterator getLatestEstimatesProcessView();

    void setPreviousLetId(String value);

    Boolean getIsFrozen();

    String getCyProbPrefillCode();
}

