package com.bayer.ipms.model.views.estimates.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 07 15:51:18 EEST 2015
// ---------------------------------------------------------------------
public interface LatestEstimatesTagView extends ViewObject {
    LatestEstimatesTagViewRow getRowById(String id);
}

