package com.bayer.ipms.model.views.estimates.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 08 17:25:17 EEST 2014
// ---------------------------------------------------------------------
public interface LatestEstimatesProjectViewRow extends Row {
    void setProjectId(String value);

    void setProcessId(String value);

    String getProjectId();

    String getProcessId();
}
