package com.bayer.ipms.model.views.imports.client;

import com.bayer.ipms.model.views.imports.common.ImportTimelineViewRow;

import oracle.jbo.RowSet;
import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 24 11:11:51 EEST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImportTimelineViewRowClient extends RowImpl implements ImportTimelineViewRow {
    /**
     * This is the default constructor (do not remove).
     */
    public ImportTimelineViewRowClient() {
    }


    public RowSet getImportActionView() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getImportActionView",null,null);
        return (RowSet)_ret;
    }

    public RowSet getImportStatusView() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getImportStatusView",null,null);
        return (RowSet)_ret;
    }

    public String getStatusCode() {
        return (String)getAttribute("StatusCode");
    }

    public String getActivityId() {
        return (String)getAttribute("ActivityId");
    }

    public String getActionCode() {
        return (String)getAttribute("ActionCode");
    }

    public String getWbsId() {
        return (String)getAttribute("WbsId");
    }
}
