package com.bayer.ipms.model.views.imports.client;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 26 18:15:00 EET 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImportStudyDataViewRowClient extends RowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ImportStudyDataViewRowClient() {
    }

    public String getImportId() {
        return (String)getAttribute("ImportId");
    }

    public void setImportId(String value) {
        setAttribute("ImportId", value);
    }

    public String getProjectId() {
        return (String)getAttribute("ProjectId");
    }

    public void setProjectId(String value) {
        setAttribute("ProjectId", value);
    }

    public String getStudyId() {
        return (String)getAttribute("StudyId");
    }

    public void setStudyId(String value) {
        setAttribute("StudyId", value);
    }

    public String getWbsId() {
        return (String)getAttribute("WbsId");
    }

    public void setWbsId(String value) {
        setAttribute("WbsId", value);
    }

    public String getName() {
        return (String)getAttribute("Name");
    }

    public void setName(String value) {
        setAttribute("Name", value);
    }

    public Date getStartDate() {
        return (Date)getAttribute("StartDate");
    }

    public void setStartDate(Date value) {
        setAttribute("StartDate", value);
    }

    public Date getFinishDate() {
        return (Date)getAttribute("FinishDate");
    }

    public void setFinishDate(Date value) {
        setAttribute("FinishDate", value);
    }

    public BigDecimal getPlaceholder() {
        return (BigDecimal)getAttribute("Placeholder");
    }

    public void setPlaceholder(BigDecimal value) {
        setAttribute("Placeholder", value);
    }

    public String getStatusCode() {
        return (String)getAttribute("StatusCode");
    }

    public void setStatusCode(String value) {
        setAttribute("StatusCode", value);
    }

    public String getStatusDescription() {
        return (String)getAttribute("StatusDescription");
    }

    public void setStatusDescription(String value) {
        setAttribute("StatusDescription", value);
    }

    public Date getCreateDate() {
        return (Date)getAttribute("CreateDate");
    }

    public void setCreateDate(Date value) {
        setAttribute("CreateDate", value);
    }

    public String getStatusName() {
        return (String)getAttribute("StatusName");
    }

    public void setStatusName(String value) {
        setAttribute("StatusName", value);
    }

    public String getActionCode() {
        return (String)getAttribute("ActionCode");
    }

    public void setActionCode(String value) {
        setAttribute("ActionCode", value);
    }

    public String getCode() {
        return (String)getAttribute("Code");
    }

    public void setCode(String value) {
        setAttribute("Code", value);
    }
}
