package com.bayer.ipms.model.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 31 16:20:17 EEST 2017
// ---------------------------------------------------------------------
public interface LtcAppModule extends ApplicationModule {

    String getCurrentLtcTagId();
    
    String getParentId();

    void refreshPreviousLtcTagProcesses();

    void initLtcExcelForm(String tagId, String processId, String programId, String projectId);

    void prefill(String tagId, String processId, String programId, String projectId);

    void commitFte();

    void commitLtc();
}

