package com.bayer.ipms.model.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 18 18:51:32 EEST 2015
// ---------------------------------------------------------------------
public interface ReportAppModule extends ApplicationModule {
    String getName();
}

