package com.bayer.ipms.model.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 18 18:52:30 EEST 2015
// ---------------------------------------------------------------------
public interface WorkspaceAppModule extends ApplicationModule {
    String getName();

    void initLeExcelForm(String tagId, String processId, String programId);

    void commitLe();
}

