package com.bayer.ipms.model.views.client;

import com.bayer.ipms.model.views.common.LtcInstanceViewRow;

import java.sql.Clob;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 27 18:02:25 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LtcInstanceViewRowClient extends RowImpl implements LtcInstanceViewRow {
    /**
     * This is the default constructor (do not remove).
     */
    public LtcInstanceViewRowClient() {
    }


    public void launch() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "launch", null, null);
        return;
    }

    public void prefill() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "prefill", null, null);
        return;
    }

    public void prefillProfit() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "prefillProfit", null, null);
        return;
    }

    public void recalculateTotals() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "recalculateTotals", null, null);
        return;
    }

    public void refresh() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "refresh", null, null);
        return;
    }

    public void submit() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "submit", null, null);
        return;
    }

    public Clob getExcelReport() {
        return (Clob) getAttribute("ExcelReport");
    }

    public String getIsReportGenerated() {
        return (String) getAttribute("IsReportGenerated");
    }

    public String getProjectId() {
        return (String) getAttribute("ProjectId");
    }

    public String getStatusCode() {
        return (String) getAttribute("StatusCode");
    }

    public void setStageNumber(Integer value) {
        setAttribute("StageNumber", value);
    }

    public void setStatusCode(String value) {
        setAttribute("StatusCode", value);
    }
}
