package com.bayer.ipms.model.views.client;

import com.bayer.ipms.model.views.common.NewsViewRow;

import oracle.jbo.RowSet;
import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 10 18:26:26 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NewsViewRowClient extends RowImpl implements NewsViewRow {
    /**
     * This is the default constructor (do not remove).
     */
    public NewsViewRowClient() {
    }

    public RowSet getNewsCategoryView() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getNewsCategoryView",null,null);
        return (RowSet)_ret;
    }
}
