package com.bayer.ipms.model.views.client;

import com.bayer.ipms.model.views.common.PhaseMilestoneView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 14 10:04:39 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PhaseMilestoneViewClient extends ViewUsageImpl implements PhaseMilestoneView {
    /**
     * This is the default constructor (do not remove).
     */
    public PhaseMilestoneViewClient() {
    }

    public String getCategoryVar() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getCategoryVar",null,null);
        return (String)_ret;
    }
}
