package com.bayer.ipms.model.views.client;

import com.bayer.ipms.model.views.common.ProjectGTView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 06 15:49:43 EET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProjectGTViewClient extends ViewUsageImpl implements ProjectGTView {
    /**
     * This is the default constructor (do not remove).
     */
    public ProjectGTViewClient() {
    }

    public void recalculateGenericTimelines() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"recalculateGenericTimelines",null,null);
        return;
    }
}
