package com.bayer.ipms.model.views.client;

import com.bayer.ipms.model.views.common.TimelineViewRow;

import java.sql.Clob;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 28 09:54:46 EEST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TimelineViewRowClient extends RowImpl implements TimelineViewRow {
    /**
     * This is the default constructor (do not remove).
     */
    public TimelineViewRowClient() {
    }


    public void deleteStudies() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "deleteStudies", null, null);
        return;
    }

    public RowSet getBaseLineTypeView() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getBaseLineTypeView", null, null);
        return (RowSet) _ret;
    }

    public RowIterator getSensorView() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getSensorView", null, null);
        return (RowIterator) _ret;
    }

    public RowIterator getTimelineBaselineView() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getTimelineBaselineView", null, null);
        return (RowIterator) _ret;
    }

    public boolean isBusy() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "isBusy", null, null);
        return ((Boolean) _ret).booleanValue();
    }

    public void publish() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "publish", null, null);
        return;
    }

    public void receive() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "receive", null, null);
        return;
    }

    public void receiveStudies() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "receiveStudies", null, null);
        return;
    }

    public void refresh() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "refresh", null, null);
        return;
    }

    public void unlock() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "unlock", null, null);
        return;
    }

    public String getBaselineTypeId() {
        return (String) getAttribute("BaselineTypeId");
    }

    public Clob getExcelReport() {
        return (Clob) getAttribute("ExcelReport");
    }

    public String getId() {
        return (String) getAttribute("Id");
    }

    public Boolean getIsPaConflict() {
        return (Boolean) getAttribute("IsPaConflict");
    }

    public Boolean getIsSyncing() {
        return (Boolean) getAttribute("IsSyncing");
    }

    public String getMaxLtcProcessId() {
        return (String) getAttribute("MaxLtcProcessId");
    }

    public String getReferenceId() {
        return (String) getAttribute("ReferenceId");
    }

    public String getSyncId() {
        return (String) getAttribute("SyncId");
    }

    public String getTypeCode() {
        return (String) getAttribute("TypeCode");
    }

    public void setBaselineTypeId(String value) {
        setAttribute("BaselineTypeId", value);
    }

    public void setIsSyncing(Boolean value) {
        setAttribute("IsSyncing", value);
    }

    public void setMaxLtcProcessId(String value) {
        setAttribute("MaxLtcProcessId", value);
    }
}
