<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ns1="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ipms-qplan="http://xmlns.bayer.com/ipms/qplan" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ipms-soa="http://xmlns.bayer.com/ipms/soa" xmlns:qplan="https://quickplan-p.bayer-ag.com/services" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:i0="https://by-quickplan-p.bayer-ag.com/services" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:ipms="http://xmlns.bayer.com/ipms" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl wsa ns1 wsa10 soap12 soapenc soap wsdl wsx wsap wsaw ipms-qplan ipms-soa qplan plnk wsp i0 msc ipms wsu xsd wsam xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../ReadPlaceholderStudies.wsdl"/>
            <oracle-xsl-mapper:rootElement name="callQPlan" namespace="http://xmlns.bayer.com/ipms/qplan"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../Interface.svc.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetStudyListResponse" namespace="https://quickplan-p.bayer-ag.com/services"/>
            <oracle-xsl-mapper:param name="GetStudyList_Output.parameters"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../ReadPlaceholderStudies.wsdl"/>
            <oracle-xsl-mapper:rootElement name="timeline" namespace="http://xmlns.bayer.com/ipms"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON JUN 01 10:43:30 CEST 2015].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="GetStudyList_Output.parameters"/>
  <xsl:template match="/">
    <ipms:timeline>
      <xsl:attribute name="projectId">
        <xsl:value-of select="/ipms-qplan:callQPlan/ipms-qplan:readPlaceholderStudies/@projectId"/>
      </xsl:attribute>
      <xsl:attribute name="id">
        <xsl:value-of select="/ipms-qplan:callQPlan/ipms-qplan:readPlaceholderStudies/@projectId"/>
        <xsl:text disable-output-escaping="no">-FPS-Placeholders</xsl:text>
      </xsl:attribute>
      <ipms:wbsNodes>
        <xsl:for-each select="$GetStudyList_Output.parameters/qplan:GetStudyListResponse/qplan:GetStudyListResult/qplan:studyData/qplan:study">
          <ipms:wbs>
            <xsl:attribute name="studyId">
              <xsl:value-of select="qplan:studyId"/>
            </xsl:attribute>
            <xsl:attribute name="placeholder">
              <xsl:text disable-output-escaping="no">true</xsl:text>
            </xsl:attribute>
            <ipms:name>
              <xsl:value-of select="qplan:name"/>
            </ipms:name>
            <ipms:startDate>
              <xsl:value-of select="qplan:studyInfo/qplan:plannedFinish"/>
            </ipms:startDate>
            <ipms:finishDate>
              <xsl:value-of select="qplan:studyInfo/qplan:plannedStart"/>
            </ipms:finishDate>
            <xsl:if test="qplan:studyInfo/qplan:studyPhase and not(qplan:studyInfo/qplan:studyPhase/@xsi:nil)">
              <ipms:studyPhase>
                <xsl:value-of select="qplan:studyInfo/qplan:studyPhase"/>
              </ipms:studyPhase>
            </xsl:if>
          </ipms:wbs>
        </xsl:for-each>
      </ipms:wbsNodes>
    </ipms:timeline>
  </xsl:template>
</xsl:stylesheet>