<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ns2="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:client="http://xmlns.bayer.com/ipms/qplan" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:qplan="https://quickplan-p.bayer-ag.com/services" xmlns:ipms-soa="http://xmlns.bayer.com/ipms/soa" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:i0="https://by-quickplan-p.bayer-ag.com/services" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:ipms="http://xmlns.bayer.com/ipms" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl wsa ns2 wsa10 soap12 soapenc plnk soap wsdl wsx wsap wsaw client qplan ipms-soa wsp i0 msc ipms wsu xsd wsam xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../ReadTimeline.wsdl"/>
            <oracle-xsl-mapper:rootElement name="callQPlan" namespace="http://xmlns.bayer.com/ipms/qplan"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../Interface.svc.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetTimelineDataResponse" namespace="https://quickplan-p.bayer-ag.com/services"/>
            <oracle-xsl-mapper:param name="GetTimelineData_Out.parameters"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../ReadTimeline.wsdl"/>
            <oracle-xsl-mapper:rootElement name="timeline" namespace="http://xmlns.bayer.com/ipms"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON JUN 01 10:43:30 CEST 2015].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="GetTimelineData_Out.parameters"/>
  <xsl:template match="/">
    <ipms:timeline>
      <xsl:attribute name="projectId">
        <xsl:value-of select="/client:callQPlan/client:readTimeline/@projectId"/>
      </xsl:attribute>
      <xsl:attribute name="id">
        <xsl:text disable-output-escaping="no">-FPS</xsl:text>
        <xsl:value-of select="/client:callQPlan/client:readTimeline/@projectId"/>
      </xsl:attribute>
      <ipms:name>
        <xsl:text disable-output-escaping="no"> FPS timeline</xsl:text>
        <xsl:value-of select="/client:callQPlan/client:readTimeline/@projectCode"/>
      </ipms:name>
      <ipms:typeCode>
        <xsl:text disable-output-escaping="no">RAW</xsl:text>
      </ipms:typeCode>
      <ipms:activities>
        <xsl:for-each select="$GetTimelineData_Out.parameters/qplan:GetTimelineDataResponse/qplan:GetTimelineDataResult/qplan:timelineData/qplan:timelineInfo">
          <ipms:activity>
            <xsl:attribute name="studyElementId">
              <xsl:value-of select="qplan:mappingCode"/>
            </xsl:attribute>
            <xsl:attribute name="id">
              <xsl:text disable-output-escaping="no">tmp</xsl:text>
            </xsl:attribute>
            <xsl:if test="qplan:plannedStart">
              <ipms:planStart>
                <xsl:value-of select="qplan:plannedStart"/>
              </ipms:planStart>
            </xsl:if>
            <xsl:if test="qplan:plannedFinish">
              <ipms:planFinish>
                <xsl:value-of select="qplan:plannedFinish"/>
              </ipms:planFinish>
            </xsl:if>
            <xsl:if test="qplan:actualStart">
              <ipms:actualStart>
                <xsl:value-of select="qplan:actualStart"/>
              </ipms:actualStart>
            </xsl:if>
            <xsl:if test="qplan:actualFinish">
              <ipms:actualFinish>
                <xsl:value-of select="qplan:actualFinish"/>
              </ipms:actualFinish>
            </xsl:if>
            <xsl:if test="qplan:dateStatus">
              <ipms:dateStatus>
                <xsl:value-of select="qplan:dateStatus"/>
              </ipms:dateStatus>
            </xsl:if>
          </ipms:activity>
        </xsl:for-each>
      </ipms:activities>
    </ipms:timeline>
  </xsl:template>
</xsl:stylesheet>