package com.bayer.ipms.model.views.ltc;

import com.bayer.ipms.model.base.IPMSViewObjectImpl;
import com.bayer.ipms.model.views.ltc.common.LtcEstimateView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 12 17:28:25 EEST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LtcEstimateViewImpl extends IPMSViewObjectImpl implements LtcEstimateView {
    /**
     * This is the default constructor (do not remove).
     */
    public LtcEstimateViewImpl() {
    }

    /**
     * Returns the bind variable value for TagIdVar.
     * @return bind variable value for TagIdVar
     */
    public String getTagIdVar() {
        return (String) getNamedWhereClauseParam("TagIdVar");
    }

    /**
     * Sets <code>value</code> for bind variable TagIdVar.
     * @param value value to bind as TagIdVar
     */
    public void setTagIdVar(String value) {
        setNamedWhereClauseParam("TagIdVar", value);
    }

    /**
     * Returns the bind variable value for ProjectIdVar.
     * @return bind variable value for ProjectIdVar
     */
    public String getProjectIdVar() {
        return (String) getNamedWhereClauseParam("ProjectIdVar");
    }

    /**
     * Sets <code>value</code> for bind variable ProjectIdVar.
     * @param value value to bind as ProjectIdVar
     */
    public void setProjectIdVar(String value) {
        setNamedWhereClauseParam("ProjectIdVar", value);
    }

    /**
     * Returns the bind variable value for ProgramIdVar.
     * @return bind variable value for ProgramIdVar
     */
    public String getProgramIdVar() {
        return (String) getNamedWhereClauseParam("ProgramIdVar");
    }

    /**
     * Sets <code>value</code> for bind variable ProgramIdVar.
     * @param value value to bind as ProgramIdVar
     */
    public void setProgramIdVar(String value) {
        setNamedWhereClauseParam("ProgramIdVar", value);
    }
    
    public void setup(String tagId, String processId, String programId, String projectId, String typeCode) {
        runStatement("begin ltc_sheet_pkg.setup(?,?,?,?,?); end;", true,tagId,processId,programId,projectId,typeCode);
    }

    /**
     * Returns the bind variable value for ProcessIdVar.
     * @return bind variable value for ProcessIdVar
     */
    public String getProcessIdVar() {
        return (String) getNamedWhereClauseParam("ProcessIdVar");
    }

    /**
     * Sets <code>value</code> for bind variable ProcessIdVar.
     * @param value value to bind as ProcessIdVar
     */
    public void setProcessIdVar(String value) {
        setNamedWhereClauseParam("ProcessIdVar", value);
    }

    /**
     * Returns the bind variable value for TypeVar.
     * @return bind variable value for TypeVar
     */
    public String getTypeVar() {
        return (String) getNamedWhereClauseParam("TypeVar");
    }

    /**
     * Sets <code>value</code> for bind variable TypeVar.
     * @param value value to bind as TypeVar
     */
    public void setTypeVar(String value) {
        setNamedWhereClauseParam("TypeVar", value);
    }
}

