package com.bayer.ipms.model.views.ltc;

import com.bayer.ipms.model.base.IPMSViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 28 12:51:17 EEST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LtcProjectViewImpl extends IPMSViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LtcProjectViewImpl() {
    }

    /**
     * Returns the bind variable value for CurrentTagIdVar.
     * @return bind variable value for CurrentTagIdVar
     */
    public String getCurrentTagIdVar() {
        return (String) getNamedWhereClauseParam("CurrentTagIdVar");
    }

    /**
     * Sets <code>value</code> for bind variable CurrentTagIdVar.
     * @param value value to bind as CurrentTagIdVar
     */
    public void setCurrentTagIdVar(String value) {
        setNamedWhereClauseParam("CurrentTagIdVar", value);
    }
}

