package com.bayer.ipms.model.views.ltc.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 12 17:29:40 EEST 2017
// ---------------------------------------------------------------------
public interface LtcEstimateView extends ViewObject {

    String getProcessIdVar();

    String getTagIdVar();

    String getProgramIdVar();

    String getProjectIdVar();

    String getTypeVar();

    void setup(String tagId, String processId, String programId, String projectId, String typeCode);
}

