package com.bayer.ipms.model.views.ltc.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 05 19:05:45 EEST 2018
// ---------------------------------------------------------------------
public interface LtcEstimateViewRow extends Row {
    void removeFakeRow();
}

