package com.bayer.ipms.model.views.ltc.common;

import java.math.BigDecimal;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 28 12:46:42 EEST 2017
// ---------------------------------------------------------------------
public interface LtcProjectViewRow extends Row {
    String getProjectId();

    void setProjectId(String value);

    BigDecimal getLtcProcessId();

    void setLtcProcessId(BigDecimal value);

    Integer getId();
}

