<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://xmlns.bayer.com/ipms/p6"
     xmlns:ns1="http://xmlns.bayer.com/ipms/p6"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="ProjectXService">
        <plnk:role name="ProjectPortType">
            <plnk:portType name="ns1:ProjectPortType"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.bayer.com/ipms/p6" location="oramds:/apps/com/bayer/xmlns/ipms/p6/ProjectService.wsdl"/>
</wsdl:definitions>
