<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ProjectProfileService"
     targetNamespace="http://xmlns.oracle.com/Primavera/P6/WS/ProjectProfile/V1"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:tns="http://xmlns.oracle.com/Primavera/P6/WS/ProjectProfile/V1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="ProjectProfileService">
        <plnk:role name="ProjectProfilePortType">
            <plnk:portType name="tns:ProjectProfilePortType"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/Primavera/P6/WS/ProjectProfile/V1" location="oramds:/apps/com/oracle/xmlns/Primavera/P6/WS/ProjectProfile/V1/ProjectProfileService.wsdl"/>
</wsdl:definitions>
