<wsdl:definitions
     name="RequestService"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/AQ/IPMS/soa/RequestService"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/AQ/IPMS/soa/RequestService"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:msg_out="http://xmlns.bayer.com/ipms/soa"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    >
  <plt:partnerLinkType name="dequeue_plt" >
    <plt:role name="dequeue_role" >
      <plt:portType name="tns:dequeue_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.bayer.com/ipms/soa" schemaLocation="oramds:/apps/com/bayer/xmlns/ipms/soa/soa.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="request_msg">
        <wsdl:part name="request" element="msg_out:request"/>
    </wsdl:message>
    <wsdl:portType name="dequeue_ptt">
        <wsdl:operation name="dequeue">
            <wsdl:input message="tns:request_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
