<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="UDFValueService"
     targetNamespace="http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="UDFValueService">
        <plnk:role name="UDFValuePortType" portType="tns:UDFValuePortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1" location="oramds:/apps/com/oracle/xmlns/Primavera/P6/WS/UDFValue/V1/UDFValueService.wsdl"/>
</wsdl:definitions>
