package com.bayer.ipms.model.views;

import com.bayer.ipms.model.base.IPMSEntityImpl;
import com.bayer.ipms.model.base.IPMSViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 13 11:39:43 EEST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CostsProbabilityViewRowImpl extends IPMSViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CreateDate {
            public Object get(CostsProbabilityViewRowImpl obj) {
                return obj.getCreateDate();
            }

            public void put(CostsProbabilityViewRowImpl obj, Object value) {
                obj.setCreateDate((Date)value);
            }
        }
        ,
        CreateUserId {
            public Object get(CostsProbabilityViewRowImpl obj) {
                return obj.getCreateUserId();
            }

            public void put(CostsProbabilityViewRowImpl obj, Object value) {
                obj.setCreateUserId((String)value);
            }
        }
        ,
        Id {
            public Object get(CostsProbabilityViewRowImpl obj) {
                return obj.getId();
            }

            public void put(CostsProbabilityViewRowImpl obj, Object value) {
                obj.setId((String)value);
            }
        }
        ,
        Probability {
            public Object get(CostsProbabilityViewRowImpl obj) {
                return obj.getProbability();
            }

            public void put(CostsProbabilityViewRowImpl obj, Object value) {
                obj.setProbability((Integer)value);
            }
        }
        ,
        ScopeCode {
            public Object get(CostsProbabilityViewRowImpl obj) {
                return obj.getScopeCode();
            }

            public void put(CostsProbabilityViewRowImpl obj, Object value) {
                obj.setScopeCode((String)value);
            }
        }
        ,
        UpdateDate {
            public Object get(CostsProbabilityViewRowImpl obj) {
                return obj.getUpdateDate();
            }

            public void put(CostsProbabilityViewRowImpl obj, Object value) {
                obj.setUpdateDate((Date)value);
            }
        }
        ,
        UpdateUserId {
            public Object get(CostsProbabilityViewRowImpl obj) {
                return obj.getUpdateUserId();
            }

            public void put(CostsProbabilityViewRowImpl obj, Object value) {
                obj.setUpdateUserId((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(CostsProbabilityViewRowImpl object);

        public abstract void put(CostsProbabilityViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int CREATEUSERID = AttributesEnum.CreateUserId.index();
    public static final int ID = AttributesEnum.Id.index();
    public static final int PROBABILITY = AttributesEnum.Probability.index();
    public static final int SCOPECODE = AttributesEnum.ScopeCode.index();
    public static final int UPDATEDATE = AttributesEnum.UpdateDate.index();
    public static final int UPDATEUSERID = AttributesEnum.UpdateUserId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CostsProbabilityViewRowImpl() {
    }

    /**
     * Gets CostsProbability entity object.
     * @return the CostsProbability
     */
    public IPMSEntityImpl getCostsProbability() {
        return (IPMSEntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for CREATE_DATE using the alias name CreateDate.
     * @return the CREATE_DATE
     */
    public Date getCreateDate() {
        return (Date)getAttributeInternal(CREATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_DATE using the alias name CreateDate.
     * @param value value to set the CREATE_DATE
     */
    public void setCreateDate(Date value) {
        setAttributeInternal(CREATEDATE, value);
    }

    /**
     * Gets the attribute value for CREATE_USER_ID using the alias name CreateUserId.
     * @return the CREATE_USER_ID
     */
    public String getCreateUserId() {
        return (String) getAttributeInternal(CREATEUSERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_USER_ID using the alias name CreateUserId.
     * @param value value to set the CREATE_USER_ID
     */
    public void setCreateUserId(String value) {
        setAttributeInternal(CREATEUSERID, value);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public String getId() {
        return (String) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(String value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for PROBABILITY using the alias name Probability.
     * @return the PROBABILITY
     */
    public Integer getProbability() {
        return (Integer)getAttributeInternal(PROBABILITY);
    }

    /**
     * Sets <code>value</code> as attribute value for PROBABILITY using the alias name Probability.
     * @param value value to set the PROBABILITY
     */
    public void setProbability(Integer value) {
        setAttributeInternal(PROBABILITY, value);
    }

    /**
     * Gets the attribute value for SCOPE_CODE using the alias name ScopeCode.
     * @return the SCOPE_CODE
     */
    public String getScopeCode() {
        return (String) getAttributeInternal(SCOPECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SCOPE_CODE using the alias name ScopeCode.
     * @param value value to set the SCOPE_CODE
     */
    public void setScopeCode(String value) {
        setAttributeInternal(SCOPECODE, value);
    }

    /**
     * Gets the attribute value for UPDATE_DATE using the alias name UpdateDate.
     * @return the UPDATE_DATE
     */
    public Date getUpdateDate() {
        return (Date)getAttributeInternal(UPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATE_DATE using the alias name UpdateDate.
     * @param value value to set the UPDATE_DATE
     */
    public void setUpdateDate(Date value) {
        setAttributeInternal(UPDATEDATE, value);
    }

    /**
     * Gets the attribute value for UPDATE_USER_ID using the alias name UpdateUserId.
     * @return the UPDATE_USER_ID
     */
    public String getUpdateUserId() {
        return (String) getAttributeInternal(UPDATEUSERID);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATE_USER_ID using the alias name UpdateUserId.
     * @param value value to set the UPDATE_USER_ID
     */
    public void setUpdateUserId(String value) {
        setAttributeInternal(UPDATEUSERID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
