package com.bayer.ipms.model.views;

import com.bayer.ipms.model.base.IPMSEntityImpl;
import com.bayer.ipms.model.base.IPMSViewRowImpl;

import com.bayer.ipms.model.views.common.LicenseViewRow;

import java.sql.Date;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 10 18:25:24 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LicenseViewRowImpl extends IPMSViewRowImpl implements LicenseViewRow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CreateDate {
            public Object get(LicenseViewRowImpl obj) {
                return obj.getCreateDate();
            }

            public void put(LicenseViewRowImpl obj, Object value) {
                obj.setCreateDate((Date)value);
            }
        }
        ,
        CreateUserId {
            public Object get(LicenseViewRowImpl obj) {
                return obj.getCreateUserId();
            }

            public void put(LicenseViewRowImpl obj, Object value) {
                obj.setCreateUserId((String)value);
            }
        }
        ,
        ExpiryDate {
            public Object get(LicenseViewRowImpl obj) {
                return obj.getExpiryDate();
            }

            public void put(LicenseViewRowImpl obj, Object value) {
                obj.setExpiryDate((Date)value);
            }
        }
        ,
        Id {
            public Object get(LicenseViewRowImpl obj) {
                return obj.getId();
            }

            public void put(LicenseViewRowImpl obj, Object value) {
                obj.setId((String)value);
            }
        }
        ,
        ProjectId {
            public Object get(LicenseViewRowImpl obj) {
                return obj.getProjectId();
            }

            public void put(LicenseViewRowImpl obj, Object value) {
                obj.setProjectId((String)value);
            }
        }
        ,
        RegionCode {
            public Object get(LicenseViewRowImpl obj) {
                return obj.getRegionCode();
            }

            public void put(LicenseViewRowImpl obj, Object value) {
                obj.setRegionCode((String)value);
            }
        }
        ,
        TypeCode {
            public Object get(LicenseViewRowImpl obj) {
                return obj.getTypeCode();
            }

            public void put(LicenseViewRowImpl obj, Object value) {
                obj.setTypeCode((String)value);
            }
        }
        ,
        UpdateDate {
            public Object get(LicenseViewRowImpl obj) {
                return obj.getUpdateDate();
            }

            public void put(LicenseViewRowImpl obj, Object value) {
                obj.setUpdateDate((Date)value);
            }
        }
        ,
        UpdateUserId {
            public Object get(LicenseViewRowImpl obj) {
                return obj.getUpdateUserId();
            }

            public void put(LicenseViewRowImpl obj, Object value) {
                obj.setUpdateUserId((String)value);
            }
        }
        ,
        TypeName {
            public Object get(LicenseViewRowImpl obj) {
                return obj.getTypeName();
            }

            public void put(LicenseViewRowImpl obj, Object value) {
                obj.setTypeName((String)value);
            }
        }
        ,
        _TypeCode {
            public Object get(LicenseViewRowImpl obj) {
                return obj.get_TypeCode();
            }

            public void put(LicenseViewRowImpl obj, Object value) {
                obj.set_TypeCode((String)value);
            }
        }
        ,
        RegionName {
            public Object get(LicenseViewRowImpl obj) {
                return obj.getRegionName();
            }

            public void put(LicenseViewRowImpl obj, Object value) {
                obj.setRegionName((String)value);
            }
        }
        ,
        _RegionCode {
            public Object get(LicenseViewRowImpl obj) {
                return obj.get_RegionCode();
            }

            public void put(LicenseViewRowImpl obj, Object value) {
                obj.set_RegionCode((String)value);
            }
        }
        ,
        RegionView {
            public Object get(LicenseViewRowImpl obj) {
                return obj.getRegionView();
            }

            public void put(LicenseViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LicenseTypeView {
            public Object get(LicenseViewRowImpl obj) {
                return obj.getLicenseTypeView();
            }

            public void put(LicenseViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(LicenseViewRowImpl object);

        public abstract void put(LicenseViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int CREATEUSERID = AttributesEnum.CreateUserId.index();
    public static final int EXPIRYDATE = AttributesEnum.ExpiryDate.index();
    public static final int ID = AttributesEnum.Id.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int REGIONCODE = AttributesEnum.RegionCode.index();
    public static final int TYPECODE = AttributesEnum.TypeCode.index();
    public static final int UPDATEDATE = AttributesEnum.UpdateDate.index();
    public static final int UPDATEUSERID = AttributesEnum.UpdateUserId.index();
    public static final int TYPENAME = AttributesEnum.TypeName.index();
    public static final int _TYPECODE = AttributesEnum._TypeCode.index();
    public static final int REGIONNAME = AttributesEnum.RegionName.index();
    public static final int _REGIONCODE = AttributesEnum._RegionCode.index();
    public static final int REGIONVIEW = AttributesEnum.RegionView.index();
    public static final int LICENSETYPEVIEW = AttributesEnum.LicenseTypeView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LicenseViewRowImpl() {
    }

    /**
     * Gets License entity object.
     * @return the License
     */
    public IPMSEntityImpl getLicense() {
        return (IPMSEntityImpl)getEntity(0);
    }

    /**
     * Gets LicenseType entity object.
     * @return the LicenseType
     */
    public IPMSEntityImpl getLicenseType() {
        return (IPMSEntityImpl)getEntity(1);
    }

    /**
     * Gets Region entity object.
     * @return the Region
     */
    public IPMSEntityImpl getRegion() {
        return (IPMSEntityImpl)getEntity(2);
    }

    /**
     * Gets the attribute value for CREATE_DATE using the alias name CreateDate.
     * @return the CREATE_DATE
     */
    public Date getCreateDate() {
        return (Date) getAttributeInternal(CREATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_DATE using the alias name CreateDate.
     * @param value value to set the CREATE_DATE
     */
    public void setCreateDate(Date value) {
        setAttributeInternal(CREATEDATE, value);
    }

    /**
     * Gets the attribute value for CREATE_USER_ID using the alias name CreateUserId.
     * @return the CREATE_USER_ID
     */
    public String getCreateUserId() {
        return (String) getAttributeInternal(CREATEUSERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_USER_ID using the alias name CreateUserId.
     * @param value value to set the CREATE_USER_ID
     */
    public void setCreateUserId(String value) {
        setAttributeInternal(CREATEUSERID, value);
    }

    /**
     * Gets the attribute value for EXPIRY_DATE using the alias name ExpiryDate.
     * @return the EXPIRY_DATE
     */
    public Date getExpiryDate() {
        return (Date) getAttributeInternal(EXPIRYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPIRY_DATE using the alias name ExpiryDate.
     * @param value value to set the EXPIRY_DATE
     */
    public void setExpiryDate(Date value) {
        setAttributeInternal(EXPIRYDATE, value);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public String getId() {
        return (String) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(String value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public String getProjectId() {
        return (String) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(String value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for REGION_CODE using the alias name RegionCode.
     * @return the REGION_CODE
     */
    public String getRegionCode() {
        return (String) getAttributeInternal(REGIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for REGION_CODE using the alias name RegionCode.
     * @param value value to set the REGION_CODE
     */
    public void setRegionCode(String value) {
        setAttributeInternal(REGIONCODE, value);
    }

    /**
     * Gets the attribute value for TYPE_CODE using the alias name TypeCode.
     * @return the TYPE_CODE
     */
    public String getTypeCode() {
        return (String) getAttributeInternal(TYPECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPE_CODE using the alias name TypeCode.
     * @param value value to set the TYPE_CODE
     */
    public void setTypeCode(String value) {
        setAttributeInternal(TYPECODE, value);
    }

    /**
     * Gets the attribute value for UPDATE_DATE using the alias name UpdateDate.
     * @return the UPDATE_DATE
     */
    public Date getUpdateDate() {
        return (Date) getAttributeInternal(UPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATE_DATE using the alias name UpdateDate.
     * @param value value to set the UPDATE_DATE
     */
    public void setUpdateDate(Date value) {
        setAttributeInternal(UPDATEDATE, value);
    }

    /**
     * Gets the attribute value for UPDATE_USER_ID using the alias name UpdateUserId.
     * @return the UPDATE_USER_ID
     */
    public String getUpdateUserId() {
        return (String) getAttributeInternal(UPDATEUSERID);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATE_USER_ID using the alias name UpdateUserId.
     * @param value value to set the UPDATE_USER_ID
     */
    public void setUpdateUserId(String value) {
        setAttributeInternal(UPDATEUSERID, value);
    }

    /**
     * Gets the attribute value for NAME using the alias name TypeName.
     * @return the NAME
     */
    public String getTypeName() {
        return (String) getAttributeInternal(TYPENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME using the alias name TypeName.
     * @param value value to set the NAME
     */
    public void setTypeName(String value) {
        setAttributeInternal(TYPENAME, value);
    }

    /**
     * Gets the attribute value for CODE using the alias name _TypeCode.
     * @return the CODE
     */
    public String get_TypeCode() {
        return (String) getAttributeInternal(_TYPECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CODE using the alias name _TypeCode.
     * @param value value to set the CODE
     */
    public void set_TypeCode(String value) {
        setAttributeInternal(_TYPECODE, value);
    }

    /**
     * Gets the attribute value for NAME using the alias name RegionName.
     * @return the NAME
     */
    public String getRegionName() {
        return (String) getAttributeInternal(REGIONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME using the alias name RegionName.
     * @param value value to set the NAME
     */
    public void setRegionName(String value) {
        setAttributeInternal(REGIONNAME, value);
    }

    /**
     * Gets the attribute value for CODE using the alias name _RegionCode.
     * @return the CODE
     */
    public String get_RegionCode() {
        return (String) getAttributeInternal(_REGIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CODE using the alias name _RegionCode.
     * @param value value to set the CODE
     */
    public void set_RegionCode(String value) {
        setAttributeInternal(_REGIONCODE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RegionView.
     */
    public RowSet getRegionView() {
        return (RowSet)getAttributeInternal(REGIONVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LicenseTypeView.
     */
    public RowSet getLicenseTypeView() {
        return (RowSet)getAttributeInternal(LICENSETYPEVIEW);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
