package com.bayer.ipms.model.views;

import com.bayer.ipms.model.base.IPMSViewObjectImpl;
import com.bayer.ipms.model.services.common.ProgramAppModule;
import com.bayer.ipms.model.utils.U;
import com.bayer.ipms.model.views.common.LtcInstanceViewRow;
import com.bayer.ipms.model.views.common.LtcValueView;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 29 13:26:59 EET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LtcValueViewImpl extends IPMSViewObjectImpl implements LtcValueView {
    /**
     * This is the default constructor (do not remove).
     */
    public LtcValueViewImpl() {
    }

    /**
     * Returns the bind variable value for projectId.
     * @return bind variable value for projectId
     */
    public String getprojectId() {
        return (String) getNamedWhereClauseParam("projectId");
    }

    /**
     * Sets <code>value</code> for bind variable projectId.
     * @param value value to bind as projectId
     */
    public void setprojectId(String value) {
        setNamedWhereClauseParam("projectId", value);
    }

    public String getCurrProjectId() {
        LtcInstanceViewRow ltciRow =
            (LtcInstanceViewRow) ((ProgramAppModule) this.getApplicationModule()).getLtcInstanceView().getCurrentRow();
        return ltciRow.getProjectId();
    }
}

