package com.bayer.ipms.model.views;

import com.bayer.ipms.model.base.IPMSViewObjectImpl;
import com.bayer.ipms.model.views.common.PhaseMilestoneView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 13 16:29:04 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PhaseMilestoneViewImpl extends IPMSViewObjectImpl implements PhaseMilestoneView {
    /**
     * This is the default constructor (do not remove).
     */
    public PhaseMilestoneViewImpl() {
    }


    /**
     * Returns the variable value for CategoryVar.
     * @return variable value for CategoryVar
     */
    public String getCategoryVar() {
        return (String)ensureVariableManager().getVariableValue("CategoryVar");
    }

    /**
     * Sets <code>value</code> for variable CategoryVar.
     * @param value value to bind as CategoryVar
     */
    public void setCategoryVar(String value) {
        ensureVariableManager().setVariableValue("CategoryVar", value);
    }
}
