package com.bayer.ipms.model.views;

import com.bayer.ipms.model.base.IPMSEntityImpl;
import com.bayer.ipms.model.base.IPMSViewRowImpl;
import com.bayer.ipms.model.views.common.ProjectRelatedMspViewRow;


import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 25 15:37:47 CET 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProjectRelatedMspViewRowImpl extends IPMSViewRowImpl implements ProjectRelatedMspViewRow {


    public static final int ENTITY_PROJECTRELATEDMSP = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        RelMspProjectId,
        ProjectId;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int RELMSPPROJECTID = AttributesEnum.RelMspProjectId.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ProjectRelatedMspViewRowImpl() {
    }

    /**
     * Gets ProjectRelatedMsp entity object.
     * @return the ProjectRelatedMsp
     */
    public IPMSEntityImpl getProjectRelatedMsp() {
        return (IPMSEntityImpl) getEntity(ENTITY_PROJECTRELATEDMSP);
    }


    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public String getId() {
        return (String) getAttributeInternal(ID);
    }


    /**
     * Gets the attribute value for REL_MSP_PROJECT_ID using the alias name RelMspProjectId.
     * @return the REL_MSP_PROJECT_ID
     */
    public String getRelMspProjectId() {
        return (String) getAttributeInternal(RELMSPPROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for REL_MSP_PROJECT_ID using the alias name RelMspProjectId.
     * @param value value to set the REL_MSP_PROJECT_ID
     */
    public void setRelMspProjectId(String value) {
        setAttributeInternal(RELMSPPROJECTID, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public String getProjectId() {
        return (String) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(String value) {
        setAttributeInternal(PROJECTID, value);
    }


}

