package com.bayer.ipms.model.views;

import com.bayer.ipms.model.base.IPMSViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 16 14:50:06 BST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProjectMemberViewImpl extends IPMSViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProjectMemberViewImpl() {
        this.showSql = true;
    }
}

