package com.bayer.ipms.model.views;

import com.bayer.ipms.model.base.IPMSEntityImpl;
import com.bayer.ipms.model.base.IPMSViewRowImpl;
import com.bayer.ipms.model.views.common.ProjectRelatedPredecessorViewRow;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 13 15:11:10 CET 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProjectRelatedPredecessorViewRowImpl extends IPMSViewRowImpl implements ProjectRelatedPredecessorViewRow {


    public static final int ENTITY_PROJECTRELATEDPREDECESSOR = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        ProjectId,
        RelPredecessorProjectId;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int RELPREDECESSORPROJECTID = AttributesEnum.RelPredecessorProjectId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ProjectRelatedPredecessorViewRowImpl() {
    }

    /**
     * Gets ProjectRelatedPredecessor entity object.
     * @return the ProjectRelatedPredecessor
     */
    public IPMSEntityImpl getProjectRelatedPredecessor() {
        return (IPMSEntityImpl) getEntity(ENTITY_PROJECTRELATEDPREDECESSOR);
    }


    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public String getId() {
        return (String) getAttributeInternal(ID);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public String getProjectId() {
        return (String) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(String value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for PREDECESSOR_PROJECT_ID using the alias name RelPredecessorProjectId.
     * @return the PREDECESSOR_PROJECT_ID
     */
    public String getRelPredecessorProjectId() {
        return (String) getAttributeInternal(RELPREDECESSORPROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for REL_PREDECESSOR_PROJECT_ID using the alias name PredecessorProjectId.
     * @param value value to set the REL_PREDECESSOR_PROJECT_ID
     */
    public void setRelPredecessorProjectId(String value) {
        setAttributeInternal(RELPREDECESSORPROJECTID, value);
    }
}

