package com.bayer.ipms.model.views;

import com.bayer.ipms.model.base.IPMSEntityImpl;
import com.bayer.ipms.model.base.IPMSViewRowImpl;


import com.bayer.ipms.model.views.common.AssignmentViewRow;
import com.bayer.ipms.model.views.common.ProgramViewRow;
import com.bayer.ipms.model.views.common.ProjectViewRow;
import com.bayer.ipms.model.views.common.SubstanceCodeAssignmentViewRow;
import com.bayer.ipms.model.views.common.TeamMemberViewRow;

import java.math.BigDecimal;

import java.sql.Date;

import java.util.Arrays;


import java.util.HashSet;
import java.util.Set;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.AttributeList;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.domain.Array;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 19 16:52:17 EET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TeamMemberViewRowImpl extends IPMSViewRowImpl implements TeamMemberViewRow {

    public static final int ENTITY_TEAMMEMBER = 0;
    public static String d2ProgramCode = "RESERVED-PT-D2-PRJ";
    public static final int ENTITY_EMPLOYEE = 1;
    public static final int ENTITY_TEAMROLE = 2;

    private ADFLogger logger = ADFLogger.createADFLogger(this.getClass().getName());

    @Override
    protected void initDefaults() {
        super.initDefaults();
    }


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getId();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProgramId {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getProgramId();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setProgramId((String) value);
            }
        }
        ,
        RoleCode {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getRoleCode();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setRoleCode((String) value);
            }
        }
        ,
        _RoleCode {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.get_RoleCode();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.set_RoleCode((String) value);
            }
        }
        ,
        RoleName {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getRoleName();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EmployeeCode {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getEmployeeCode();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setEmployeeCode((String) value);
            }
        }
        ,
        SearchEmployeeCode {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getSearchEmployeeCode();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        _EmployeeCode {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.get_EmployeeCode();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.set_EmployeeCode((String) value);
            }
        }
        ,
        EmployeeName {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getEmployeeName();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setEmployeeName((String) value);
            }
        }
        ,
        SearchEmployeeName {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getSearchEmployeeName();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UpdateUserId {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getUpdateUserId();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UpdateDate {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getUpdateDate();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreateUserId {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getCreateUserId();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreateDate {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getCreateDate();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UserRoleCode {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getUserRoleCode();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        HasProject {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getHasProject();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AssignedProjectIds {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getAssignedProjectIds();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAssignedProjectIds((Array) value);
            }
        }
        ,
        EmployeeNameSort {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getEmployeeNameSort();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProgramView {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getProgramView();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AssignmentView {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getAssignmentView();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DevTeamRoleView {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getDevTeamRoleView();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EmployeeView {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getEmployeeView();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        D2PrjTeamRoleView {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getD2PrjTeamRoleView();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrdMntTeamRoleView {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getPrdMntTeamRoleView();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SAMDTeamRoleView {
            protected Object get(TeamMemberViewRowImpl obj) {
                return obj.getSAMDTeamRoleView();
            }

            protected void put(TeamMemberViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;


        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }


        protected abstract Object get(TeamMemberViewRowImpl object);

        protected abstract void put(TeamMemberViewRowImpl object, Object value);
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int PROGRAMID = AttributesEnum.ProgramId.index();
    public static final int ROLECODE = AttributesEnum.RoleCode.index();
    public static final int _ROLECODE = AttributesEnum._RoleCode.index();
    public static final int ROLENAME = AttributesEnum.RoleName.index();
    public static final int EMPLOYEECODE = AttributesEnum.EmployeeCode.index();
    public static final int SEARCHEMPLOYEECODE = AttributesEnum.SearchEmployeeCode.index();
    public static final int _EMPLOYEECODE = AttributesEnum._EmployeeCode.index();
    public static final int EMPLOYEENAME = AttributesEnum.EmployeeName.index();
    public static final int SEARCHEMPLOYEENAME = AttributesEnum.SearchEmployeeName.index();
    public static final int UPDATEUSERID = AttributesEnum.UpdateUserId.index();
    public static final int UPDATEDATE = AttributesEnum.UpdateDate.index();
    public static final int CREATEUSERID = AttributesEnum.CreateUserId.index();
    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int USERROLECODE = AttributesEnum.UserRoleCode.index();
    public static final int HASPROJECT = AttributesEnum.HasProject.index();
    public static final int ASSIGNEDPROJECTIDS = AttributesEnum.AssignedProjectIds.index();
    public static final int EMPLOYEENAMESORT = AttributesEnum.EmployeeNameSort.index();
    public static final int PROGRAMVIEW = AttributesEnum.ProgramView.index();
    public static final int ASSIGNMENTVIEW = AttributesEnum.AssignmentView.index();
    public static final int DEVTEAMROLEVIEW = AttributesEnum.DevTeamRoleView.index();
    public static final int EMPLOYEEVIEW = AttributesEnum.EmployeeView.index();
    public static final int D2PRJTEAMROLEVIEW = AttributesEnum.D2PrjTeamRoleView.index();
    public static final int PRDMNTTEAMROLEVIEW = AttributesEnum.PrdMntTeamRoleView.index();
    public static final int SAMDTEAMROLEVIEW = AttributesEnum.SAMDTeamRoleView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TeamMemberViewRowImpl() {
    }

    /**
     * Gets TeamMember entity object.
     * @return the TeamMember
     */
    public IPMSEntityImpl getTeamMember() {
        return (IPMSEntityImpl) getEntity(0);
    }

    /**
     * Gets Employee entity object.
     * @return the Employee
     */
    public IPMSEntityImpl getEmployee() {
        return (IPMSEntityImpl) getEntity(1);
    }

    /**
     * Gets TeamRole entity object.
     * @return the TeamRole
     */
    public IPMSEntityImpl getTeamRole() {
        return (IPMSEntityImpl) getEntity(2);
    }

    /**
     * Gets the attribute value for CREATE_DATE using the alias name CreateDate.
     * @return the CREATE_DATE
     */
    public Date getCreateDate() {
        return (Date) getAttributeInternal(CREATEDATE);
    }


    /**
     * Gets the attribute value for the calculated attribute UserRoleCode.
     * @return the UserRoleCode
     */
    public String getUserRoleCode() {
        return (String) getAttributeInternal(USERROLECODE);
    }

    /**
     * Gets the attribute value for the calculated attribute HasProject.
     * @return the HasProject
     */
    public BigDecimal getHasProject() {
        return (BigDecimal) getAttributeInternal(HASPROJECT);
    }

    /**
     * Gets the attribute value for the calculated attribute EmployeeNameSort.
     * @return the EmployeeNameSort
     */
    public String getEmployeeNameSort() {
        return (String) getAttributeInternal(EMPLOYEENAMESORT);
    }


    /**
     * Gets the attribute value for CREATE_USER_ID using the alias name CreateUserId.
     * @return the CREATE_USER_ID
     */
    public String getCreateUserId() {
        return (String) getAttributeInternal(CREATEUSERID);
    }


    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public String getId() {
        return (String) getAttributeInternal(ID);
    }


    /**
     * Gets the attribute value for PROGRAM_ID using the alias name ProgramId.
     * @return the PROGRAM_ID
     */
    public String getProgramId() {
        return (String) getAttributeInternal(PROGRAMID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROGRAM_ID using the alias name ProgramId.
     * @param value value to set the PROGRAM_ID
     */
    public void setProgramId(String value) {
        setAttributeInternal(PROGRAMID, value);
    }

    /**
     * Gets the attribute value for UPDATE_DATE using the alias name UpdateDate.
     * @return the UPDATE_DATE
     */
    public Date getUpdateDate() {
        return (Date) getAttributeInternal(UPDATEDATE);
    }


    /**
     * Gets the attribute value for UPDATE_USER_ID using the alias name UpdateUserId.
     * @return the UPDATE_USER_ID
     */
    public String getUpdateUserId() {
        return (String) getAttributeInternal(UPDATEUSERID);
    }


    /**
     * Gets the attribute value for ROLE_CODE using the alias name RoleCode.
     * @return the ROLE_CODE
     */
    public String getRoleCode() {
        return (String) getAttributeInternal(ROLECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ROLE_CODE using the alias name RoleCode.
     * @param value value to set the ROLE_CODE
     */
    public void setRoleCode(String value) {
        setAttributeInternal(ROLECODE, value);
    }

    /**
     * Gets the attribute value for NAME using the alias name RoleName.
     * @return the NAME
     */
    public String getRoleName() {
        return (String) getAttributeInternal(ROLENAME);
    }


    /**
     * Gets the attribute value for CODE using the alias name _RoleCode.
     * @return the CODE
     */
    public String get_RoleCode() {
        return (String) getAttributeInternal(_ROLECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CODE using the alias name _RoleCode.
     * @param value value to set the CODE
     */
    public void set_RoleCode(String value) {
        setAttributeInternal(_ROLECODE, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_CODE using the alias name EmployeeCode.
     * @return the EMPLOYEE_CODE
     */
    public String getEmployeeCode() {
        return (String) getAttributeInternal(EMPLOYEECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_CODE using the alias name EmployeeCode.
     * @param value value to set the EMPLOYEE_CODE
     */
    public void setEmployeeCode(String value) {
        setAttributeInternal(EMPLOYEECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SearchEmployeeCode.
     * @return the SearchEmployeeCode
     */
    public String getSearchEmployeeCode() {
        return (String) getAttributeInternal(SEARCHEMPLOYEECODE);
    }

    /**
     * Gets the attribute value for CODE using the alias name _EmployeeCode.
     * @return the CODE
     */
    public String get_EmployeeCode() {
        return (String) getAttributeInternal(_EMPLOYEECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CODE using the alias name _EmployeeCode.
     * @param value value to set the CODE
     */
    public void set_EmployeeCode(String value) {
        setAttributeInternal(_EMPLOYEECODE, value);
    }

    /**
     * Gets the attribute value for NAME using the alias name EmployeeName.
     * @return the NAME
     */
    public String getEmployeeName() {
        return (String) getAttributeInternal(EMPLOYEENAME);
    }


    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EmployeeName.
     * @param value value to set the  EmployeeName
     */
    public void setEmployeeName(String value) {
        setAttributeInternal(EMPLOYEENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SearchEmployeeName.
     * @return the SearchEmployeeName
     */
    public String getSearchEmployeeName() {
        return (String) getAttributeInternal(SEARCHEMPLOYEENAME);
    }


    /**
     * Gets the attribute value for the calculated attribute AssignedProjectIds.
     * @return the AssignedProjectIds
     */
    public Array getAssignedProjectIds() {
        return (Array) getAttributeInternal(ASSIGNEDPROJECTIDS);
    }


    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AssignedProjectIds.
     * @param value value to set the  AssignedProjectIds
     */
    public void setAssignedProjectIds(Array value) {
        setAttributeInternal(ASSIGNEDPROJECTIDS, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ProgramView.
     */
    public oracle.jbo.Row getProgramView() {
        return (oracle.jbo.Row) getAttributeInternal(PROGRAMVIEW);
    }

    /**
     * Sets the master-detail link ProgramView between this object and <code>value</code>.
     */
    public void setProgramView(oracle.jbo.Row value) {
        setAttributeInternal(PROGRAMVIEW, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AssignmentView.
     */
    public RowIterator getAssignmentView() {
        return (RowIterator) getAttributeInternal(ASSIGNMENTVIEW);
    }


    /**
     * Gets the view accessor <code>RowSet</code> DevTeamRoleView.
     */
    public RowSet getDevTeamRoleView() {
        return (RowSet) getAttributeInternal(DEVTEAMROLEVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EmployeeView.
     */
    public RowSet getEmployeeView() {
        return (RowSet) getAttributeInternal(EMPLOYEEVIEW);
    }


    /**
     * Gets the view accessor <code>RowSet</code> D2PrjTeamRoleView.
     */
    public RowSet getD2PrjTeamRoleView() {
        return (RowSet) getAttributeInternal(D2PRJTEAMROLEVIEW);
    }


    /**
     * Gets the view accessor <code>RowSet</code> PrdMntTeamRoleView.
     */
    public RowSet getPrdMntTeamRoleView() {
        return (RowSet) getAttributeInternal(PRDMNTTEAMROLEVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SAMDTeamRoleView.
     */
    public RowSet getSAMDTeamRoleView() {
        return (RowSet) getAttributeInternal(SAMDTEAMROLEVIEW);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * getAssignedProjects: method used by selectManyChoice UI component to display assigned projects as checked
     */
    public String[] getAssignedProjects() {

        Array ids = getAssignedProjectIds();
        if (ids == null) {
            Set<String> idsSet = new HashSet<String>();

            RowIterator rIt = this.getAssignmentView();
            rIt.reset();
            while (rIt.hasNext()) {
                AssignmentViewRow r = (AssignmentViewRow) rIt.next();
                idsSet.add(r.getProjectId());
            }
            return idsSet.toArray(new String[0]);
        } else {
            Object[] array = ids.getArray();         
            return (String[]) Arrays.copyOf(array, array.length, String[].class);
        }

    }

    /**
     * setAssignedProjects: method used by selectManyChoice UI component to set checked projects as assigned
     */
    public void setAssignedProjects(String[] projectIds) {
        setAssignedProjectIds(new Array(projectIds != null ? projectIds : new String[0]));
    }


    public void deleteAssignment() {
        RowIterator rIt = getAssignmentView();
        rIt.reset();
        
        while (rIt.hasNext()) {
            AssignmentViewRow r = (AssignmentViewRow) rIt.next();
            if (r != null)
            r.remove();
        }
    }
    
    /**
     * updateAssignedProjects: method used to update assigned projects by creating removing assignments between current team member and projects
     */
    public void updateAssignedProjects() {

        if (getAssignedProjectIds() != null) {

            Set<String> selectedIds = new HashSet<String>(Arrays.asList(getAssignedProjects()));
            RowIterator rIt = getAssignmentView();
            rIt.reset();

            // compare selected project ids with existing ids and remove unselected ones
            while (rIt.hasNext()) {
                AssignmentViewRow r = (AssignmentViewRow) rIt.next();
                String id = r.getProjectId();
                if (selectedIds.contains(id)) {
                    // remove existing ids from set of selected ids
                    selectedIds.remove(id);
                } else {
                    // remove unselected ids
                    rIt.removeCurrentRow();
                }
            }

            // add rows for new project ids
            for (String newId : selectedIds) {
                AssignmentViewRow nr = (AssignmentViewRow) rIt.createRow();
                nr.setTeamMemberId(getId());
                nr.setProjectId(newId);
                rIt.insertRow(nr);
            }

        }
    }


}
