package com.bayer.ipms.model.views;

import com.bayer.ipms.model.base.IPMSViewRowImpl;



import com.bayer.ipms.model.views.common.TimelineBaselineViewRow;

import java.math.BigDecimal;

import java.sql.Clob;
import java.sql.Date;
import java.sql.Timestamp;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 04 16:57:35 EET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TimelineBaselineViewRowImpl extends IPMSViewRowImpl implements TimelineBaselineViewRow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TimelineLevel {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getTimelineLevel();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TimelineId {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getTimelineId();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TreeId {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getTreeId();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TimelineBaselineId {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getTimelineBaselineId();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BaselineVersion {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getBaselineVersion();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ReferenceId {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getReferenceId();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BaselineType {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getBaselineType();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BaselineDescription {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getBaselineDescription();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Name {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getName();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProjectId {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getProjectId();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TypeCode {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getTypeCode();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreateDate {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getCreateDate();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UpdateDate {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getUpdateDate();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SyncDate {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getSyncDate();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IsSyncing {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getIsSyncing();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Comments {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getComments();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BaselineLtciId {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getBaselineLtciId();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ExcelReport {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getExcelReport();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BaselineLtcProcessId {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getBaselineLtcProcessId();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BaselineLtcTagId {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getBaselineLtcTagId();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProcessDescription {
            protected Object get(TimelineBaselineViewRowImpl obj) {
                return obj.getProcessDescription();
            }

            protected void put(TimelineBaselineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;


        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }


        protected abstract Object get(TimelineBaselineViewRowImpl object);

        protected abstract void put(TimelineBaselineViewRowImpl object, Object value);
    }


    public static final int TIMELINELEVEL = AttributesEnum.TimelineLevel.index();
    public static final int TIMELINEID = AttributesEnum.TimelineId.index();
    public static final int TREEID = AttributesEnum.TreeId.index();
    public static final int TIMELINEBASELINEID = AttributesEnum.TimelineBaselineId.index();
    public static final int BASELINEVERSION = AttributesEnum.BaselineVersion.index();
    public static final int REFERENCEID = AttributesEnum.ReferenceId.index();
    public static final int BASELINETYPE = AttributesEnum.BaselineType.index();
    public static final int BASELINEDESCRIPTION = AttributesEnum.BaselineDescription.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int TYPECODE = AttributesEnum.TypeCode.index();
    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int UPDATEDATE = AttributesEnum.UpdateDate.index();
    public static final int SYNCDATE = AttributesEnum.SyncDate.index();
    public static final int ISSYNCING = AttributesEnum.IsSyncing.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int BASELINELTCIID = AttributesEnum.BaselineLtciId.index();
    public static final int EXCELREPORT = AttributesEnum.ExcelReport.index();
    public static final int BASELINELTCPROCESSID = AttributesEnum.BaselineLtcProcessId.index();
    public static final int BASELINELTCTAGID = AttributesEnum.BaselineLtcTagId.index();
    public static final int PROCESSDESCRIPTION = AttributesEnum.ProcessDescription.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TimelineBaselineViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute TimelineLevel.
     * @return the TimelineLevel
     */
    public BigDecimal getTimelineLevel() {
        return (BigDecimal) getAttributeInternal(TIMELINELEVEL);
    }

    /**
     * Gets the attribute value for the calculated attribute TimelineId.
     * @return the TimelineId
     */
    public String getTimelineId() {
        return (String) getAttributeInternal(TIMELINEID);
    }

    /**
     * Gets the attribute value for the calculated attribute TreeId.
     * @return the TreeId
     */
    public String getTreeId() {
        return (String) getAttributeInternal(TREEID);
    }

    /**
     * Gets the attribute value for the calculated attribute TimelineBaselineId.
     * @return the TimelineBaselineId
     */
    public String getTimelineBaselineId() {
        return (String) getAttributeInternal(TIMELINEBASELINEID);
    }

    /**
     * Gets the attribute value for the calculated attribute BaselineVersion.
     * @return the BaselineVersion
     */
    public Timestamp getBaselineVersion() {
        return (Timestamp) getAttributeInternal(BASELINEVERSION);
    }

    /**
     * Gets the attribute value for the calculated attribute ReferenceId.
     * @return the ReferenceId
     */
    public String getReferenceId() {
        return (String) getAttributeInternal(REFERENCEID);
    }

    /**
     * Gets the attribute value for the calculated attribute BaselineType.
     * @return the BaselineType
     */
    public String getBaselineType() {
        return (String) getAttributeInternal(BASELINETYPE);
    }

    /**
     * Gets the attribute value for the calculated attribute BaselineDescription.
     * @return the BaselineDescription
     */
    public String getBaselineDescription() {
        return (String) getAttributeInternal(BASELINEDESCRIPTION);
    }

    /**
     * Gets the attribute value for the calculated attribute Name.
     * @return the Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectId.
     * @return the ProjectId
     */
    public String getProjectId() {
        return (String) getAttributeInternal(PROJECTID);
    }

    /**
     * Gets the attribute value for the calculated attribute TypeCode.
     * @return the TypeCode
     */
    public String getTypeCode() {
        return (String) getAttributeInternal(TYPECODE);
    }

    /**
     * Gets the attribute value for the calculated attribute CreateDate.
     * @return the CreateDate
     */
    public Date getCreateDate() {
        return (Date) getAttributeInternal(CREATEDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute UpdateDate.
     * @return the UpdateDate
     */
    public Date getUpdateDate() {
        return (Date) getAttributeInternal(UPDATEDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute SyncDate.
     * @return the SyncDate
     */
    public Date getSyncDate() {
        return (Date) getAttributeInternal(SYNCDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute IsSyncing.
     * @return the IsSyncing
     */
    public Integer getIsSyncing() {
        return (Integer) getAttributeInternal(ISSYNCING);
    }

    /**
     * Gets the attribute value for the calculated attribute Comments.
     * @return the Comments
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Gets the attribute value for the calculated attribute BaselineLtciId.
     * @return the BaselineLtciId
     */
    public String getBaselineLtciId() {
        return (String) getAttributeInternal(BASELINELTCIID);
    }

    /**
     * Gets the attribute value for the calculated attribute ExcelReport.
     * @return the ExcelReport
     */
    public Clob getExcelReport() {
        return (Clob) getAttributeInternal(EXCELREPORT);
    }

    /**
     * Gets the attribute value for the calculated attribute LtcProcessId.
     * @return the LtcProcessId
     */
    public String getBaselineLtcProcessId() {
        return (String) getAttributeInternal(BASELINELTCPROCESSID);
    }

    /**
     * Gets the attribute value for the calculated attribute LtcTagId.
     * @return the LtcTagId
     */
    public String getBaselineLtcTagId() {
        return (String) getAttributeInternal(BASELINELTCTAGID);
    }

    /**
     * Gets the attribute value for the calculated attribute ProcessDescription.
     * @return the ProcessDescription
     */
    public String getProcessDescription() {
        return (String) getAttributeInternal(PROCESSDESCRIPTION);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

