<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:intgfault="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../wsdl/WBSService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ReadAllWBSResponse"
                                       namespace="http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../wsdl/WBSService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ReadWBSResponse"
                                       namespace="http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2"/>
        <oracle-xsl-mapper:param name="ReadContainerWBS_Out.result"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../wsdl/WBSService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="UpdateWBS" namespace="http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU SEP 10 10:57:29 EEST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="ReadContainerWBS_Out.result"/>
  <xsl:template match="/">
    <ns0:UpdateWBS>
      <xsl:for-each select="/ns0:ReadAllWBSResponse/ns0:WBS">
        <ns0:WBS>
          <ns0:OBSObjectId>
            <xsl:value-of select="$ReadContainerWBS_Out.result/ns0:ReadWBSResponse/ns0:WBS/ns0:OBSObjectId"/>
          </ns0:OBSObjectId>
          <ns0:ObjectId>
            <xsl:value-of select="ns0:ObjectId"/>
          </ns0:ObjectId>
        </ns0:WBS>
      </xsl:for-each>
    </ns0:UpdateWBS>
  </xsl:template>
</xsl:stylesheet>
