--------------------------------------------------------
--  File created - Wednesday-July-13-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROJECT_DIM
--------------------------------------------------------

  CREATE TABLE "IPMS_REPO"."PROJECT_DIM" 
   (	"ID" NVARCHAR2(20), 
	"PROGRAM_ID" NVARCHAR2(10), 
	"CODE" NVARCHAR2(20), 
	"NAME" NVARCHAR2(100), 
	"SHORT_NAME" NVARCHAR2(50), 
	"PROJECT_STATE_CODE" NVARCHAR2(10), 
	"PROJECT_STATE" NVARCHAR2(100), 
	"IS_ACTIVE" NUMBER(1,0), 
	"IS_LEAD" NUMBER(1,0), 
	"LE_OVERVIEW_CODE" NVARCHAR2(10), 
	"LE_OVERVIEW" NVARCHAR2(100), 
	"SBE_CODE" NVARCHAR2(10), 
	"SBE" NVARCHAR2(100), 
	"GBU_CODE" NVARCHAR2(10), 
	"GBU" NVARCHAR2(100), 
	"THERAPEUTIC_AREA_CODE" NVARCHAR2(10), 
	"THERAPEUTIC_AREA" NVARCHAR2(100), 
	"PROJECT_AREA_CODE" NVARCHAR2(10), 
	"PROJECT_AREA" NVARCHAR2(100), 
	"PHASE_CODE" NVARCHAR2(10), 
	"PHASE" NVARCHAR2(100), 
	"PRIORITY_CODE" NVARCHAR2(10), 
	"PRIORITY" NVARCHAR2(100), 
	"LC_TYPE_CODE" NVARCHAR2(20), 
	"LC_TYPE" NVARCHAR2(100), 
	"SUBGROUP_CODE" NVARCHAR2(20), 
	"SUBGROUP_NAME" NVARCHAR2(100), 
	"MAINGROUP_CODE" NVARCHAR2(20), 
	"MAINGROUP_NAME" NVARCHAR2(200), 
	"SUBSTANCE_TYPE_CODE" NVARCHAR2(10), 
	"SUBSTANCE_TYPE" NVARCHAR2(100), 
	"SOURCE_CODE" NVARCHAR2(20), 
	"SOURCE" NVARCHAR2(100), 
	"TARGET_CLASS_CODE" NVARCHAR2(10), 
	"TARGET_CLASS" NVARCHAR2(100), 
	"TARGET_ORIGIN_CODE" NVARCHAR2(10), 
	"TARGET_ORIGIN" NVARCHAR2(100), 
	"ENPV" NUMBER(20,10), 
	"NPV" NUMBER(20,10), 
	"PEAK_SALES" NUMBER(20,10), 
	"PORTFOLIO_PROJECT" NUMBER(1,0), 
	"HPR" NUMBER(1,0), 
	"IS_REGIONAL" NUMBER(1,0), 
	"IS_ORPHAN_DRUG" NUMBER(1,0), 
	"COLLABORATION" NUMBER(1,0), 
	"PIP_PROJECT" NUMBER(1,0), 
	"PIP_DATE" DATE, 
	"PDCO_DATE" DATE, 
	"IS_PDCO_POSITIVE" NUMBER(1,0), 
	"IS_WAIVER" NUMBER(1,0), 
	"PIP_ACTIVITIES" NVARCHAR2(2000), 
	"TERMINATION_NAME" NVARCHAR2(100), 
	"TERMINATION_CODE" NVARCHAR2(10), 
	"TERMINATION_DATE" DATE, 
	"TERMINATION_REASON" NVARCHAR2(500), 
	"PTS_PRECLINICAL" NUMBER(20,0), 
	"PTS_PHASE1" NUMBER(20,0), 
	"PTS_PHASE2" NUMBER(20,0), 
	"PTS_PHASE3" NUMBER(20,0), 
	"PTS_SUBMISSION" NUMBER(20,0), 
	"PTS_TOTAL" NUMBER, 
	"REVIEW_MEETING_DATE" DATE, 
	"DETAILS_PARTNER" NVARCHAR2(2000), 
	"DETAILS_PROGRESS" NVARCHAR2(2000), 
	"PROGRESS_DATE" DATE, 
	"DETAILS_CRITERIA" NVARCHAR2(2000), 
	"DETAILS_MESH" NVARCHAR2(2000), 
	"DETAILS_INDICATION" NVARCHAR2(2000), 
	"DETAILS_PRODUCT" NVARCHAR2(2000), 
	"DETAILS_GOAL" NVARCHAR2(2000), 
	"DETAILS_ACTION" NVARCHAR2(2000), 
	"DETAILS_COMPETITION" NVARCHAR2(2000), 
	"DETAILS_PATENT" NVARCHAR2(2000), 
	"DETAILS_SALES" NVARCHAR2(2000), 
	"DETAILS_PMO" NVARCHAR2(2000), 
	"DETAILS_COMMENT" NVARCHAR2(2000), 
	"DETAILS_MODALITY" VARCHAR2(4000 BYTE), 
	"COMBINATION_CODE" NVARCHAR2(10), 
	"COMBINATION_ID" NVARCHAR2(100), 
	"PREFERRED_BAY_NO" NVARCHAR2(100), 
	"P6_RAW_PLAN" NVARCHAR2(24), 
	"P6_CURRENT_PLAN" NVARCHAR2(24), 
	"P6_APPROVED_PLAN" NVARCHAR2(24), 
	"PLANNING_ENABLED" NVARCHAR2(20), 
	"IP_OWNER_CODE" NVARCHAR2(20), 
	"IP_OWNER" NVARCHAR2(200), 
	"D1_MILESTONE_FOR_D1_PRJ" DATE, 
	"D1_GOAL_FACTOR_FOR_D1_PRJ" NUMBER, 
	"START_HTS_MILESTONE" DATE, 
	"LSA_DATE" DATE, 
	"TERMINATION_GOAL_FACTOR" NUMBER, 
	"D2_COMPOUND" NVARCHAR2(80), 
	"SUCCESSOR_PROJECT_ID" NVARCHAR2(30), 
	"PREDECESSOR_PROJECT_ID" NVARCHAR2(30), 
	"D3TRANSITION_PROJECT_ID" NVARCHAR2(30), 
	"LO_REVIEW_MEETING_DATE" DATE, 
	"LO_REVIEW_RESULT_CODE" NVARCHAR2(20), 
	"THERAPEUTIC_RESEARCH_GROUP" NVARCHAR2(256), 
	"TARGET_GENE_CODE" NVARCHAR2(250), 
	"EXPLORATORY_RESEARCH" NVARCHAR2(250), 
	"GENERAL_PROJECT_FRAME" NVARCHAR2(250), 
	"PHASE_ESTIMATED_CODE" NVARCHAR2(20), 
	"PHASE_ESTIMATED" NVARCHAR2(100), 
	"PTR_FOR_D2_CODE" NVARCHAR2(15), 
	"PTR_FOR_D3_CODE" NVARCHAR2(10), 
	"PREVIOUS_NAMES" NVARCHAR2(4000), 
	"DEVICE_PROJECT" NUMBER(1,0), 
	"BPI_NO" VARCHAR2(256 BYTE), 
	"PROJECT_DEVICE_TYPE_CODE" VARCHAR2(10 BYTE), 
	"PROJECT_DEVICE_TYPE_NAME" VARCHAR2(100 BYTE), 
	"REGULATORY_CODE" VARCHAR2(800 BYTE), 
	"REGULATORY_NAME" VARCHAR2(100 BYTE), 
	"REGULATORY_OTHER" VARCHAR2(1000 BYTE), 
	"DEVICE_PHASE_CODE" VARCHAR2(20 BYTE), 
	"DEVICE_PHASE_NAME" VARCHAR2(100 BYTE), 
	"DET_OBJECTIVE_MSP" NVARCHAR2(2000), 
	"DET_RATIONALE_MSP" NVARCHAR2(2000), 
	"DET_SCOPE_MSP" NVARCHAR2(2000), 
	"DET_INTENDED_USE_MSP" NVARCHAR2(2000), 
	"DET_BENEFITS_MSP" NVARCHAR2(2000), 
	"DET_EXECUTIVE_SUMMARY_MSP" NVARCHAR2(2000), 
	"DET_RISKS_MSP" NVARCHAR2(2000), 
	"DET_HIGHLIGHTS_MSP" NVARCHAR2(2000), 
	"DET_ACTIVITIES_EVENTS_MSP" NVARCHAR2(2000), 
	"DET_BUDGET_MSP" NVARCHAR2(2000), 
	"DET_SAMD_STATUS_MSP" NVARCHAR2(100), 
	"DET_SAMD_STATUS_CODE_MSP" NVARCHAR2(2000), 
	"DET_BUDGET_STATUS_MSP" NVARCHAR2(100), 
	"DET_BUDGET_STATUS_CODE_MSP" NVARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"   NO INMEMORY ;
  GRANT SELECT ON "IPMS_REPO"."PROJECT_DIM" TO "MYCSD";
--------------------------------------------------------
--  Constraints for Table PROJECT_DIM
--------------------------------------------------------

  ALTER TABLE "IPMS_REPO"."PROJECT_DIM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "IPMS_REPO"."PROJECT_DIM" MODIFY ("PROGRAM_ID" NOT NULL ENABLE);
  ALTER TABLE "IPMS_REPO"."PROJECT_DIM" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "IPMS_REPO"."PROJECT_DIM" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "IPMS_REPO"."PROJECT_DIM" MODIFY ("IS_LEAD" NOT NULL ENABLE);
  ALTER TABLE "IPMS_REPO"."PROJECT_DIM" MODIFY ("PORTFOLIO_PROJECT" NOT NULL ENABLE);
  ALTER TABLE "IPMS_REPO"."PROJECT_DIM" MODIFY ("HPR" NOT NULL ENABLE);
  ALTER TABLE "IPMS_REPO"."PROJECT_DIM" MODIFY ("IS_REGIONAL" NOT NULL ENABLE);
  ALTER TABLE "IPMS_REPO"."PROJECT_DIM" MODIFY ("IS_ORPHAN_DRUG" NOT NULL ENABLE);
  ALTER TABLE "IPMS_REPO"."PROJECT_DIM" MODIFY ("COLLABORATION" NOT NULL ENABLE);
  ALTER TABLE "IPMS_REPO"."PROJECT_DIM" MODIFY ("PIP_PROJECT" NOT NULL ENABLE);
  ALTER TABLE "IPMS_REPO"."PROJECT_DIM" MODIFY ("IS_PDCO_POSITIVE" NOT NULL ENABLE);
  ALTER TABLE "IPMS_REPO"."PROJECT_DIM" MODIFY ("IS_WAIVER" NOT NULL ENABLE);
  ALTER TABLE "IPMS_REPO"."PROJECT_DIM" MODIFY ("DEVICE_PROJECT" NOT NULL ENABLE);
