<wsdl:definitions
     name="updateTask"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ipms-mw/ipms.p6x/updateTask"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ipms-mw/ipms.p6x/updateTask"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/updateTask"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="updateTask_plt" >
    <plt:role name="updateTask_role" >
      <plt:portType name="tns:updateTask_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/updateTask" schemaLocation="Schemas/updateTask.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="updateTaskInput_msg">
        <wsdl:part name="updateTaskInput_msg" element="db:updateTaskInput"/>
    </wsdl:message>
    <wsdl:portType name="updateTask_ptt">
        <wsdl:operation name="updateTask">
            <wsdl:input message="tns:updateTaskInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
