CREATE TABLE "IPMS_DATA"."QPLAN_ELEMENT_TYPE" 
("CODE" NVARCHAR2(50) NOT NULL ENABLE, 
"NAME" NVARCHAR2(100) NOT NULL ENABLE, 
"ORDER_BY" NUMBER(4,0) DEFAULT 50 NOT NULL ENABLE, 
"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
"MILESTONE_CODE" NVARCHAR2(10), 
CONSTRAINT "PROJECT_AREA_CONFIG_TYPE_PK" PRIMARY KEY ("CODE"));

CREATE TABLE "IPMS_DATA"."PROJECT_AREA_QPLAN_CONFIG" 
("AREA_CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
"ELEMENT_CODE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
"IS_MANDATORY" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
);

CREATE UNIQUE INDEX "IPMS_DATA"."PROJECT_AREA_CONFIG_UI" ON "IPMS_DATA"."PROJECT_AREA_QPLAN_CONFIG" ("AREA_CODE", "ELEMENT_CODE");