ALTER TABLE PROJECT_AREA_QPLAN_CONFIG MODIFY (AREA_CODE NVARCHAR2(20) );

ALTER TABLE PROJECT_AREA_QPLAN_CONFIG MODIFY (ELEMENT_CODE NVARCHAR2(50) );

ALTER TABLE PROJECT_AREA_QPLAN_CONFIG
ADD CONSTRAINT PROJECT_AREA_QPLAN_CONFIG_FK1 FOREIGN KEY ( ELEMENT_CODE )
REFERENCES QPLAN_ELEMENT_TYPE
(CODE ) ENABLE;