CREATE TABLE "IPMS_DATA"."PROJECT_RELATION" 
("FROM_ID" NVARCHAR2(20) NOT NULL ENABLE, 
"TO_ID" NVARCHAR2(20) NOT NULL ENABLE, 
"CREATE_USER_ID" NVARCHAR2(20) DEFAULT 'IPMS' NOT NULL ENABLE, 
"UPDATE_USER_ID" NVARCHAR2(20), 
"CREATE_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
"UPDATE_DATE" DATE, 
CONSTRAINT "PROJECT_RELATION_FROM_ID_FK" FOREIGN KEY ("FROM_ID")
REFERENCES "IPMS_DATA"."PROJECT" ("ID") ON DELETE CASCADE ENABLE, 
CONSTRAINT "PROJECT_RELATION_TO_ID_FK" FOREIGN KEY ("TO_ID")
REFERENCES "IPMS_DATA"."PROJECT" ("ID") ON DELETE CASCADE ENABLE
);

COMMENT ON COLUMN "IPMS_DATA"."PROJECT_RELATION"."FROM_ID" IS 'FROM must be older than TO, based on project life cycle, starting from GPF, D1, D2, etc., e.g.: FROM=D2 and TO=DEV but not in different direction.';

CREATE UNIQUE INDEX "IPMS_DATA"."PROJECT_RELATION_UI" ON "IPMS_DATA"."PROJECT_RELATION" ("FROM_ID", "TO_ID");

ALTER TABLE PROJECT ADD(PIDT_RELEASE_DATE DATE);
ALTER TABLE PROJECT_AREA ADD (IS_PIDT NUMBER(1) DEFAULT 0 NOT NULL);
COMMENT ON COLUMN PROJECT_AREA.IS_PIDT IS 'Must this project AREA be exported/released to PIDT?';
ALTER TABLE PROJECT ADD(PLANNING_CODE NVARCHAR2(20));