alter table project disable all triggers;
alter table project add (lo_review_meeting_date date);
alter table project add (lo_review_result_code nvarchar2(20) check(lo_review_result_code in ('Red','Yellow','Green')) );
comment on column project.lo_review_result_code is 'Needed for D2 projects: Review Date + Review Results (Red/Yellow/Green). Latest Review Date is sufficient (Review Date can be overwritten).';
alter table project add (start_hts_date date);
alter table project add (D2_COMPOUND nvarchar2(80));
comment on column project.D2_COMPOUND is 'D2 Compound';
alter table project add (TRG nvarchar2(250));
comment on column project.TRG is 'Therapeutic Research Group';
alter table project add (TARGET_GENE_CODE nvarchar2(250));
comment on column project.TARGET_GENE_CODE is 'Target Gene Code. Available';
alter table project add (ER nvarchar2(250));
comment on column project.ER is 'Exploratory Research';
alter table project add (GENERAL_PROJECT_FRAME nvarchar2(250));
comment on column project.GENERAL_PROJECT_FRAME is 'General Project Frame';
alter table project add (d1_decision_date date);
alter table project add (lsa_date date);
alter table project add (display_state_code nvarchar2(81));
alter table project enable all triggers;