
  CREATE TABLE "IPMS_DATA"."GOAL" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NVARCHAR2(20) NOT NULL ENABLE, 
	"GOAL" NVARCHAR2(200) NOT NULL ENABLE, 
	"TYPE" NVARCHAR2(10) NOT NULL ENABLE, 
	"PHASE" NVARCHAR2(10) DEFAULT 'S' NOT NULL ENABLE, 
	"PLAN_REFERENCE" NVARCHAR2(32), 
	"PLAN_REFERENCE_DATE" DATE, 
	"STATUS" NVARCHAR2(10) NOT NULL ENABLE, 
	"TARGET_DATE" DATE NOT NULL ENABLE, 
	"ACHIEVED_DATE" DATE, 
	"REVISED_DATE" DATE, 
	"CREATE_DATE" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"UPDATE_DATE" TIMESTAMP (6), 
	"CREATE_USER_ID" NVARCHAR2(20) DEFAULT 'IPMS' NOT NULL ENABLE, 
	"UPDATE_USER_ID" NVARCHAR2(20), 
	"STUDY_ID" NVARCHAR2(100), 
	 CONSTRAINT "GOAL_TYPE" CHECK (type in ('T', 'K', 'B')) ENABLE, 
	 CONSTRAINT "GOAL_PHASE" CHECK (type in ('S', 'T')) ENABLE, 
	 PRIMARY KEY ("ID"), 
	 CONSTRAINT "GOAL_STATUS" FOREIGN KEY ("STATUS")
	  REFERENCES "IPMS_DATA"."GOAL_STATUS" ("CODE") ENABLE, 
	 CONSTRAINT "GOAL_PROJECT" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "IPMS_DATA"."PROJECT" ("ID") ENABLE
   );

  CREATE INDEX "IPMS_DATA"."GOAL_PROJECT" ON "IPMS_DATA"."GOAL" ("PROJECT_ID");
  CREATE INDEX "IPMS_DATA"."GOAL_STATUS" ON "IPMS_DATA"."GOAL" ("STATUS");

  CREATE SEQUENCE  "IPMS_DATA"."GOAL_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  CYCLE ;