ALTER TABLE IMPORT_MASTERDATA MODIFY PROJECT_GROUP_CODE NVARCHAR2(60);
ALTER TABLE PROJECT MODIFY PROJECT_GROUP_CODE NVARCHAR2(60);
COMMENT ON COLUMN PROJECT.PROJECT_GROUP_CODE IS 'Import Subgroup from Combase for all Projects';