create table sys_log (
	id number constraint sys_log_pk primary key,
	create_date date,
	create_user_id nvarchar2(20),
	severity nvarchar2(50),
	subject nvarchar2(4000),
	parameters nvarchar2(4000),
	content nvarchar2(4000),
	error_stack nvarchar2(4000)
)
; 
comment on table sys_log is 'Table stores system log from bacground DB actions.';
comment on column sys_log.id is 'Autogenerated surogate ID';
comment on column sys_log.subject is 'Usually it is lower case: package_name.procedure_name.';
comment on column sys_log.parameters is 'Parameters passed to procedure.';
comment on column sys_log.severity is 'Type: DEBUG,INFO,WARNING,ERROR';
comment on column sys_log.content is 'Long description of issue/fact.';
comment on column sys_log.error_stack is 'In case it is an error then separately store error stack.';
--
create sequence sys_log_id_seq maxvalue 9999999999999999999 minvalue 1 cycle;
create or replace trigger sys_log_bi_tr
before insert on sys_log for each row
begin
	select sys_log_id_seq.nextval into :new.id from dual;
	:new.create_date := sysdate;
	:new.create_user_id := nvl(:new.create_user_id,'TRIGGER');
end;
/