create table project_activity(
	id number constraint pact_pk primary key,
	project_id nvarchar2(20) constraint pact_project_id_cnn not null constraint pact_project_id_fk references project(id),
	project_activity_id varchar2(100) constraint pact_prj_activity_id_cnn not null,
	project_activity_name varchar2(240) constraint pact_prj_activity_name_cnn not null,
	study_id varchar2(20),
	p6_activity_id varchar2(100),
	plan_start_date	date,
	plan_finish_date date,
	act_start_date date,
	act_finish_date date,
	wbs_category varchar2(100),
	is_upserted number(1) constraint pact_is_upserted_check check(is_upserted in (0,1)),
	create_date date constraint pact_create_date_cnn not null,
	create_user_id nvarchar2(20) constraint pact_create_user_id_cnn not null,
	update_date date constraint pact_update_date_cnn not null,
	update_user_id nvarchar2(20) constraint pact_update_user_id_cnn not null,
	constraint pact_uk1 unique(project_id,project_activity_id,project_activity_name, wbs_category)
);
------------
create index pact_project_id_fki on project_activity(project_id);
create unique index pact_idx1 on project_activity(lower(project_id||':'||project_activity_id||':'||project_activity_name||':'|| wbs_category));
------------
comment on table project_activity is 'Project activities used for activity based planning';
comment on column project_activity.id is 'Autogenerated surogate ID.';
comment on column project_activity.project_id is 'Reference to: project(id)';
comment on column project_activity.project_activity_id is 'Project activity ID from SOPHIA';
comment on column project_activity.project_activity_name is 'Project activity name from SOPHIA';
comment on column project_activity.study_id is 'Study ID from SOPHIA';
comment on column project_activity.p6_activity_id is 'Activity ID which comes from Primavera P6';
comment on column project_activity.plan_start_date is 'Activity planned start date';
comment on column project_activity.plan_finish_date is 'Activity planned finish date';
comment on column project_activity.act_start_date is 'Activity actual start date';
comment on column project_activity.act_finish_date is 'Activity actual finish date';
comment on column project_activity.wbs_category is 'Category name';
comment on column project_activity.is_upserted is 'Service flag for DML operations';
------------
create sequence project_activity_id_seq maxvalue 9999999999999999999 minvalue 1 cycle;
-------------------------------------------------------------------------
create table import_project_activity(
	id number constraint ipact_pk primary key,
	import_id nvarchar2(20)  constraint ipact_import_id_cnn not null constraint ipact_import_id_fk references import(id),
	project_id nvarchar2(20) constraint ipact_project_id_cnn not null constraint ipact_project_id_fk references project(id),
	project_activity_id varchar2(100) constraint ipact_prj_activity_id_cnn not null,
	project_activity_name varchar2(240) constraint ipact_prj_activity_name_cnn not null,
	study_id varchar2(20),
	p6_activity_id varchar2(100),
	plan_start_date	date,
	plan_finish_date date,
	act_start_date date,
	act_finish_date date,
	milestone_code nvarchar2(10) constraint ipact_milestone_code_fk references milestone(code),
	wbs_category varchar2(100),
	status_code nvarchar2(10) default 'NEW' constraint ipact_status_code_cnn not null constraint ipact_status_code_fk references import_status(code),
	status_description varchar2(2000),
	constraint ipact_uk1 unique(import_id,project_id,project_activity_id,project_activity_name, milestone_code)
);
------------
create index ipact_project_id_fki on import_project_activity(project_id);
create index ipact_import_id_fki on import_project_activity(import_id);
------------
comment on table import_project_activity is 'Import staging table for project activities used for activity based planning';
comment on column import_project_activity.id is 'Autogenerated surogate ID.';
comment on column import_project_activity.import_id is 'Reference to: import(id)';
comment on column import_project_activity.project_id is 'Reference to: project(id)';
comment on column import_project_activity.project_activity_id is 'Project activity ID from SOPHIA';
comment on column import_project_activity.project_activity_name is 'Project activity name from SOPHIA';
comment on column import_project_activity.study_id is 'Study ID from SOPHIA';
comment on column import_project_activity.p6_activity_id is 'Activity ID which comes from Primavera P6';
comment on column import_project_activity.plan_start_date is 'Activity planned start date';
comment on column import_project_activity.plan_finish_date is 'Activity planned finish date';
comment on column import_project_activity.act_start_date is 'Activity actual start date';
comment on column import_project_activity.act_finish_date is 'Activity actual finish date';
comment on column import_project_activity.milestone_code is 'Decision start milestone code';
comment on column import_project_activity.wbs_category is 'WBS Category name resolved from milestone_code';
comment on column import_project_activity.status_code is 'Import status code';
comment on column import_project_activity.status_description is 'Import status description, providing details about particular row';
------------
create sequence import_project_activity_id_seq maxvalue 9999999999999999999 minvalue 1 cycle;
alter table timeline_activity add (create_user varchar2(100));