alter table project add is_device_project number(1,0) default 0 constraint project_is_device_prj_cnn not null;
comment on column project.is_device_project is 'The flag on which project is being merked for solecting releated device projects.';
------------
alter table project add bpi_no varchar2(256);
comment on column project.bpi_no is 'Texfield (single line) (BPI ist eine ID ähnlich zu BayNo nur für Devices).';
------------
create table project_device_type (
	code varchar2(10) not null primary key,
	name varchar2(100) not null,
	description varchar2(500),
	is_active number(1) default 1 constraint prj_device_type_act_cnn not null constraint prj_device_type_act_ca check(is_active in (0,1)),
	create_date date default sysdate not null,
	update_date date
);
------------
comment on table project_device_type is 'Table represents the lookup for Project Device Field. Table was created while implementing requirement: PROMIS-460';
comment on column project_device_type.code is 'Unique code for the type.';
comment on column project_device_type.name is 'The name of the type.';
------------
create or replace trigger project_device_type_tr
before insert or update on project_device_type
for each row
begin
	if inserting then
		:new.create_date := sysdate;
	end if;
	:new.update_date := sysdate;
end;
/
------------
insert into project_device_type (code,name) values ('combined','Drug/ Device (combined)');
insert into project_device_type (code,name) values ('alone','Device (stand alone)');
insert into project_device_type (code,name) values ('other','Other');
------------
alter table project add project_device_type_code varchar2(10) constraint project_device_type_fk references project_device_type(code);
comment on column project.project_device_type_code is 'Reference to the table project_device_type.';
------------
create index project_device_type_fki on project(project_device_type_code);
------------
create table project_device (
	id number constraint prj_device_pk primary key,
	project_id nvarchar2(20) constraint prj_device_project_id_cnn not null constraint prj_device_project_id_fk references project(id) on delete cascade,
	related_project_id nvarchar2(20) constraint prj_device_re_project_id_cnn not null constraint prj_device_re_project_id_fk references project(id) on delete cascade,
	create_date date constraint prj_device_create_date_cnn not null,
	create_user_id varchar2(20) constraint prj_device_create_by_cnn not null,
	update_date date constraint prj_device_update_date_cnn not null,
	update_user_id varchar2(20) constraint prj_device_update_by_cnn not null
);
------------
create index prj_device_project_id_fki on project_device(project_id);
create index prj_device_re_project_id_fki on project_device(related_project_id);
------------
comment on table project_device is 'Table stores all related projects for selected project along with the field: is_device_project. Table was created while implementing requirement: PROMIS-460';
comment on column project_device.id is 'Autogenerated surogate ID.';
comment on column project_device.project_id is 'The root project that was makrked at: project.is_device_project=1 (true).';
comment on column project_device.related_project_id is 'Releted project for the root project.';
------------
create sequence prj_device_id_seq maxvalue 9999999999999999999 minvalue 1 cycle;
------------
create or replace trigger project_device_tr
before insert or update on project_device
for each row
begin
	if inserting then
		if :new.id is null then
			select prj_device_id_seq.nextval into :new.id from dual;
		end if;
		:new.create_date := sysdate;
		:new.create_user_id := nvl(:new.create_user_id,'TRIGGER');
		:new.update_user_id := :new.create_user_id;
	end if;
	if updating then
		:new.update_user_id := nvl(:new.update_user_id,'TRIGGER');
	end if;
	:new.update_date := sysdate;
end;
/