
  CREATE MATERIALIZED VIEW "IPMS_REPO"."COLLABORATION_DETAILS_DIM" ("ID", "PROJECT_ID", "CODE", "PARTNER", "PARTNER_CODE", "COLLABORATION_TYPE", "COLLABORATION_TYPE_CODE", "START_PHASE", "START_PHASE_CODE", "END_PHASE", "END_PHASE_CODE", "COMMENT")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT
CD.ID, 
CD.PROJECT_ID,
PR.CODE,
(decode(CD.PARTNER_CODE,PT.CODE,PT.NAME,null))PARTNER,
CD.PARTNER_CODE,
(decode(CD.COLLABORATION_TYPE_CODE,CT.CODE,CT.NAME,null))COLLABORATION_TYPE, 
CD.COLLABORATION_TYPE_CODE,
decode(CD.START_PHASE_CODE, PH.CODE,PH.NAME ,null) START_PHASE,
CD.START_PHASE_CODE,
(decode(CD.END_PHASE_CODE,PH2.CODE,PH2.NAME ,null))END_PHASE,
CD.END_PHASE_CODE,
CD."COMMENT"
FROM IPMS_DATA.COLLABORATION_DETAILS CD, IPMS_DATA.PROJECT PR, IPMS_DATA.COLLABORATION_TYPE CT, IPMS_DATA.PARTNER PT, IPMS_DATA.PHASE PH,
IPMS_DATA.PHASE PH2
WHERE CD.PROJECT_ID = PR.ID 
and PT.CODE (+)= CD.PARTNER_CODE 
and CT.CODE (+)= CD.COLLABORATION_TYPE_CODE 
and CD.START_PHASE_CODE = PH.CODE (+)
and CD.END_PHASE_CODE = PH2.CODE(+);

   COMMENT ON MATERIALIZED VIEW "IPMS_REPO"."COLLABORATION_DETAILS_DIM"  IS 'snapshot table for snapshot IPMS_REPO.COLLABORATION_DETAILS_DIM';


  GRANT SELECT ON "IPMS_REPO"."COLLABORATION_DETAILS_DIM" TO "MYCSD";
