--------------------------------------------------------
--  DDL for Materialized View LICENSE_DETAILS_DIM
--------------------------------------------------------

  CREATE MATERIALIZED VIEW IPMS_REPO.LICENSE_DETAILS_DIM (ID, PROJECT_ID, CODE, LICENSOR, LICENSOR_CODE, LICENSEE, LICENSEE_CODE, LICENSE_TYPE, LICENSE_TYPE_CODE, LICENSE_AGREEMENT_DATE, LICENSE_COMMENT, PREDECESSOR_ID)
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS select
LD.id, 
LD.PROJECT_ID, 
PR.CODE,
(DECODE(LD.LICENSOR_CODE,PT.CODE,PT.NAME,null)) LICENSOR, 
LD.LICENSOR_CODE,
(DECODE(LD.LICENSEE_CODE,PT2.CODE,PT2.NAME,null)) LICENSEE, 
LD.LICENSEE_CODE,
(DECODE(LD.LICENSE_TYPE_CODE,LT.CODE,LT.NAME,null)) LICENSE_TYPE, 
LD.LICENSE_TYPE_CODE,
LD.LICENSE_AGREEMENT_DATE, 
LD.LICENSE_COMMENT, 
LD.PREDECESSOR_ID
from IPMS_DATA.LICENSE_DETAILS LD
left join IPMS_DATA.PARTNER PT on PT.CODE = LD.LICENSOR_CODE
left join IPMS_DATA.PARTNER PT2 on PT2.CODE = LD.LICENSEE_CODE
left join IPMS_DATA.project PR on PR.id = LD.PROJECT_ID
left join IPMS_DATA.LICENSE_DETAIL_TYPE LT on LT.CODE = LD.LICENSE_TYPE_CODE;

   COMMENT ON MATERIALIZED VIEW IPMS_REPO.LICENSE_DETAILS_DIM  IS 'snapshot table for snapshot IPMS_REPO.LICENSE_DETAILS_DIM';
  GRANT SELECT ON IPMS_REPO.LICENSE_DETAILS_DIM TO MYCSD;
