--------------------------------------------------------
--  DDL for Materialized View PROJECT_REL_SUCCESSOR_DIM
--------------------------------------------------------

  CREATE MATERIALIZED VIEW IPMS_REPO.PROJECT_REL_SUCCESSOR_DIM (ID, PROJECT_ID, CODE, SUCCESSOR_PROJECT_ID, SUCCESSOR_PROJECT_CODE)
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS select
PRS.ID, 
PRS.PROJECT_ID, 
PR.CODE,
PRS.SUCCESSOR_PROJECT_ID,
PR1.CODE SUCCESSOR_PROJECT_CODE
from ipms_data.PROJECT_RELATED_SUCCESSOR PRS
left join ipms_data.project PR on PRS.PROJECT_ID=PR.ID
left join ipms_data.project PR1 on PR1.ID=PRS.SUCCESSOR_PROJECT_ID;

   COMMENT ON MATERIALIZED VIEW IPMS_REPO.PROJECT_REL_SUCCESSOR_DIM  IS 'snapshot table for snapshot IPMS_REPO.PROJECT_REL_SUCCESSOR_DIM';
  GRANT SELECT ON IPMS_REPO.PROJECT_REL_SUCCESSOR_DIM TO MYCSD;
