--------------------------------------------------------
--  DDL for Materialized View PROJECT_REL_PREDECESSOR_DIM
--------------------------------------------------------

  CREATE MATERIALIZED VIEW IPMS_REPO.PROJECT_REL_PREDECESSOR_DIM (ID, PROJECT_ID, CODE, REL_PREDECESSOR_PROJECT_ID, PREDECESSOR_PROJECT_CODE)
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS select
PRP.ID, 
PRP.PROJECT_ID, 
PR.CODE,
PRP.REL_PREDECESSOR_PROJECT_ID,
PR1.CODE PREDECESSOR_PROJECT_CODE
from ipms_data.PROJECT_RELATED_PREDECESSOR PRP
left join ipms_data.project PR on PRP.PROJECT_ID=PR.ID
left join ipms_data.project PR1 on PR1.ID=PRP.REL_PREDECESSOR_PROJECT_ID;

   COMMENT ON MATERIALIZED VIEW IPMS_REPO.PROJECT_REL_PREDECESSOR_DIM  IS 'snapshot table for snapshot IPMS_REPO.PROJECT_REL_PREDECESSOR_DIM';
  GRANT SELECT ON IPMS_REPO.PROJECT_REL_PREDECESSOR_DIM TO MYCSD;
