--------------------------------------------------------
--  File created - Monday-February-07-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Materialized View PROJECT_RELATED_DEV_DIM
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "IPMS_REPO"."PROJECT_RELATED_DEV_DIM" ("ID", "PROJECT_ID", "DEV_PROJECT_ID")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  REFRESH FORCE ON DEMAND
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS select
   "ID", 
	"PROJECT_ID", 
	"DEV_PROJECT_ID"
from ipms_data.PROJECT_RELATED_DEV;

   COMMENT ON MATERIALIZED VIEW "IPMS_REPO"."PROJECT_RELATED_DEV_DIM"  IS 'snapshot table for snapshot IPMS_REPO.PROJECT_RELATED_DEV_DIM';
  GRANT SELECT ON "IPMS_REPO"."PROJECT_RELATED_DEV_DIM" TO "MYCSD";
