
  CREATE MATERIALIZED VIEW "IPMS_REPO"."PROJECT_ROADMAP_DIM" ("ID", "PROJECT_ID", "CODE", "DATE", "TOPIC", "DESCRIPTION")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS select
PRD.ID,
PRD.PROJECT_ID,
PR.CODE,
PRD."DATE",
PRD.TOPIC,
PRD.DESCRIPTION
from ipms_data.PROJECT_ROADMAP PRD, IPMS_DATA.PROJECT PR
WHERE PRD.PROJECT_ID = PR.ID;

   COMMENT ON MATERIALIZED VIEW "IPMS_REPO"."PROJECT_ROADMAP_DIM"  IS 'snapshot table for snapshot IPMS_REPO.PROJECT_ROADMAP_DIM';


  GRANT SELECT ON "IPMS_REPO"."PROJECT_ROADMAP_DIM" TO "MYCSD";
