<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:ns0="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:tns="https://quickplan-p.bayer-ag.com/services" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:i0="https://by-quickplan-p.bayer-ag.com/services" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl wsa ns0 wsa10 soap12 soapenc soap wsdl wsx wsap wsaw tns wsp i0 msc xsd wsu wsam xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../Interface.svc.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetTimelineData" namespace="https://quickplan-p.bayer-ag.com/services"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../Interface.svc.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetTimelineDataResponse" namespace="https://quickplan-p.bayer-ag.com/services"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON JUN 01 10:43:26 CEST 2015].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <tns:GetTimelineDataResponse>
      <tns:GetTimelineDataResult>
        <tns:timelineData>
          <tns:timelineInfo>
            <tns:actualFinish>2012-03-09</tns:actualFinish>
            <tns:actualStart>2011-05-09</tns:actualStart>
            <tns:dateStatus>Finished</tns:dateStatus>
            <tns:mappingCode>3200</tns:mappingCode>
            <tns:plannedFinish>2013-05-13</tns:plannedFinish>
          </tns:timelineInfo>
          <tns:timelineInfo>
            <tns:actualFinish>2012-05-03</tns:actualFinish>
            <tns:actualStart>2012-04-10</tns:actualStart>
            <tns:dateStatus>Finished</tns:dateStatus>
            <tns:mappingCode>3700</tns:mappingCode>
          </tns:timelineInfo>
          <tns:timelineInfo>
            <tns:actualFinish>2012-08-21</tns:actualFinish>
            <tns:actualStart>2011-12-13</tns:actualStart>
            <tns:dateStatus>In Progress</tns:dateStatus>
            <tns:mappingCode>3500</tns:mappingCode>
            <tns:plannedFinish>2013-06-24</tns:plannedFinish>
            <tns:plannedStart>2013-05-13</tns:plannedStart>
          </tns:timelineInfo>
          <tns:timelineInfo>
            <tns:dateStatus>Planned</tns:dateStatus>
            <tns:mappingCode>2500</tns:mappingCode>
            <tns:plannedFinish>2017-01-10</tns:plannedFinish>
            <tns:plannedStart>2013-09-16</tns:plannedStart>
          </tns:timelineInfo>

          <tns:timelineInfo>
            <tns:actualFinish>2014-06-09</tns:actualFinish>
            <tns:actualStart>2014-05-09</tns:actualStart>
            <tns:dateStatus>Finished</tns:dateStatus>
            <tns:mappingCode>4000</tns:mappingCode>
            <tns:plannedFinish>2013-06-13</tns:plannedFinish>
            <tns:plannedStart>2013-05-13</tns:plannedStart>
          </tns:timelineInfo>
          <tns:timelineInfo>
            <tns:dateStatus>Planned</tns:dateStatus>
            <tns:mappingCode>2600</tns:mappingCode>
            <tns:plannedStart>2013-09-16</tns:plannedStart>
          </tns:timelineInfo>
          <tns:timelineInfo>
            <tns:actualStart>2010-05-09</tns:actualStart>
            <tns:dateStatus>Planned</tns:dateStatus>
            <tns:mappingCode>2050</tns:mappingCode>
            <tns:plannedFinish>2014-06-03</tns:plannedFinish>
            <tns:plannedStart>2014-05-03</tns:plannedStart>
          </tns:timelineInfo>
          <tns:timelineInfo>
            <tns:actualStart>2010-02-01</tns:actualStart>
            <tns:dateStatus>Planned</tns:dateStatus>
            <tns:mappingCode>2850</tns:mappingCode>
            <tns:plannedFinish>2015-06-01</tns:plannedFinish>
            <tns:plannedStart>2015-01-01</tns:plannedStart>
          </tns:timelineInfo>
          <tns:timelineInfo>
            <tns:dateStatus>Planned</tns:dateStatus>
            <tns:mappingCode>3604</tns:mappingCode>
            <tns:plannedFinish>2015-06-02</tns:plannedFinish>
            <tns:plannedStart>2015-01-02</tns:plannedStart>
          </tns:timelineInfo>
          <tns:timelineInfo>
            <tns:dateStatus>Planned</tns:dateStatus>
            <tns:mappingCode>4650</tns:mappingCode>
            <tns:plannedFinish>2015-06-03</tns:plannedFinish>
            <tns:plannedStart>2015-01-03</tns:plannedStart>
          </tns:timelineInfo>
        </tns:timelineData>
      </tns:GetTimelineDataResult>
    </tns:GetTimelineDataResponse>
  </xsl:template>
</xsl:stylesheet>