package com.bayer.ipms.model.services;

import com.bayer.ipms.model.base.IPMSApplicationModuleImpl;
import com.bayer.ipms.model.base.IPMSViewObjectImpl;
import com.bayer.ipms.model.services.common.EstimatesAppModule;
import com.bayer.ipms.model.views.ProgramViewImpl;
import com.bayer.ipms.model.views.ProjectViewImpl;
import com.bayer.ipms.model.views.estimates.LatestEstimatesProcessViewImpl;
import com.bayer.ipms.model.views.estimates.common.LatestEstimatesTagViewRow;

import com.bayer.ipms.model.views.lookups.ProjectAreaViewImpl;

import oracle.jbo.server.ViewLinkImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 16 10:40:28 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EstimatesAppModuleImpl extends IPMSApplicationModuleImpl implements EstimatesAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public EstimatesAppModuleImpl() {
    }

    /**
     * Container's getter for DevProgramView.
     * @return DevProgramView
     */
    public ProgramViewImpl getDevProgramView() {
        return (ProgramViewImpl) findViewObject("DevProgramView");
    }

    /**
     * Container's getter for PrdMntProgramView.
     * @return PrdMntProgramView
     */
    public ProgramViewImpl getPrdMntProgramView() {
        return (ProgramViewImpl) findViewObject("PrdMntProgramView");
    }

    /**
     * Container's getter for D3TrProjectView.
     * @return D3TrProjectView
     */
    public ProjectViewImpl getD3TrProjectView() {
        return (ProjectViewImpl) findViewObject("D3TrProjectView");
    }

    /**
     * Container's getter for LatestEstimatesTagView.
     * @return LatestEstimatesTagView
     */
    public IPMSViewObjectImpl getLatestEstimatesTagView() {
        return (IPMSViewObjectImpl) findViewObject("LatestEstimatesTagView");
    }

    /**
     * Container's getter for LatestEstimatesProcessView.
     * @return LatestEstimatesProcessView
     */
    public LatestEstimatesProcessViewImpl getLatestEstimatesProcessView() {
        return (LatestEstimatesProcessViewImpl) findViewObject("LatestEstimatesProcessView");
    }

    /**
     * Container's getter for LatestEstimatesProjectView.
     * @return LatestEstimatesProjectView
     */
    public IPMSViewObjectImpl getLatestEstimatesProjectView() {
        return (IPMSViewObjectImpl) findViewObject("LatestEstimatesProjectView");
    }

    


    /**
     * Container's getter for LepLet.
     * @return LepLet
     */
    public ViewLinkImpl getLepLet() {
        return (ViewLinkImpl) findViewLink("LepLet");
    }

    /**
     * Container's getter for EstimatesProcessProjects.
     * @return EstimatesProcessProjects
     */
    public ViewLinkImpl getEstimatesProcessProjects() {
        return (ViewLinkImpl) findViewLink("EstimatesProcessProjects");
    }

  


    public String getCurrentLeTagId() {

        if (getLatestEstimatesTagView().getCurrentRow() != null) {
            return ((LatestEstimatesTagViewRow) getLatestEstimatesTagView().getCurrentRow()).getId();
        } else {
            return null;
        }
    }
    
    public String getPreviousLeTagId() {

        if (getLatestEstimatesTagView().getCurrentRow() != null) {
            return ((LatestEstimatesTagViewRow) getLatestEstimatesTagView().getCurrentRow()).getPreviousLetId();
        } else {
            return null;
        }
    }

    /**
     * Container's getter for ProjectAreaView2.
     * @return ProjectAreaView2
     */
    public ProjectAreaViewImpl getDevProjectAreaView() {
        return (ProjectAreaViewImpl) findViewObject("DevProjectAreaView");
    }

    public String getName() {
        return super.getName();
    }


    /**
     * Container's getter for LatestEstimatesProcessView1.
     * @return LatestEstimatesProcessView1
     */
    public LatestEstimatesProcessViewImpl getPreviousTagLatestEstimatesProcessView() {
        return (LatestEstimatesProcessViewImpl) findViewObject("PreviousTagLatestEstimatesProcessView");
    }
    
    public void refreshPreviousLeTagProcesses(){
        
        getPreviousTagLatestEstimatesProcessView().executeQuery();
        
        }
}

