package com.bayer.ipms.model.services;

import com.bayer.ipms.model.base.IPMSApplicationModuleImpl;
import com.bayer.ipms.model.base.IPMSViewObjectImpl;
import com.bayer.ipms.model.services.common.SharedAppModule;
import com.bayer.ipms.model.views.CostsProbabilityDefaultViewImpl;
import com.bayer.ipms.model.views.RoleViewImpl;
import com.bayer.ipms.model.views.UserViewImpl;
import com.bayer.ipms.model.views.lookups.BaseLineTypeViewImpl;
import com.bayer.ipms.model.views.lookups.ConfigurationViewImpl;

import com.bayer.ipms.model.views.lookups.FunctionViewImpl;

import com.bayer.ipms.model.views.lookups.ProjectAreaViewImpl;


import oracle.jbo.server.ViewLinkImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 18 18:51:45 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SharedAppModuleImpl extends IPMSApplicationModuleImpl implements SharedAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public SharedAppModuleImpl() {
    }

    /**
     * Container's getter for GlobalBusinessUnitView.
     * @return GlobalBusinessUnitView
     */
    public IPMSViewObjectImpl getGlobalBusinessUnitView() {
        return (IPMSViewObjectImpl) findViewObject("GlobalBusinessUnitView");
    }

    /**
     * Container's getter for ImportActionView.
     * @return ImportActionView
     */
    public IPMSViewObjectImpl getImportActionView() {
        return (IPMSViewObjectImpl) findViewObject("ImportActionView");
    }

    /**
     * Container's getter for NoticeSeverityView.
     * @return NoticeSeverityView
     */
    public IPMSViewObjectImpl getNoticeSeverityView() {
        return (IPMSViewObjectImpl) findViewObject("NoticeSeverityView");
    }

    /**
     * Container's getter for MilestoneView.
     * @return MilestoneView
     */
    public IPMSViewObjectImpl getMilestoneView() {
        return (IPMSViewObjectImpl) findViewObject("MilestoneView");
    }

    /**
     * Container's getter for PhaseView.
     * @return PhaseView
     */
    public IPMSViewObjectImpl getPhaseView() {
        return (IPMSViewObjectImpl) findViewObject("PhaseView");
    }

    /**
     * Container's getter for ProjectCategoryView.
     * @return ProjectCategoryView
     */
    public IPMSViewObjectImpl getProjectCategoryView() {
        return (IPMSViewObjectImpl) findViewObject("ProjectCategoryView");
    }

    /**
     * Container's getter for ProjectSourceView.
     * @return ProjectSourceView
     */
    public IPMSViewObjectImpl getProjectSourceView() {
        return (IPMSViewObjectImpl) findViewObject("ProjectSourceView");
    }

    /**
     * Container's getter for RegionView.
     * @return RegionView
     */
    public IPMSViewObjectImpl getRegionView() {
        return (IPMSViewObjectImpl) findViewObject("RegionView");
    }

    /**
     * Container's getter for SubstanceTypeView.
     * @return SubstanceTypeView
     */
    public IPMSViewObjectImpl getSubstanceTypeView() {
        return (IPMSViewObjectImpl) findViewObject("SubstanceTypeView");
    }

    /**
     * Container's getter for TerminationReasonView.
     * @return TerminationReasonView
     */
    public IPMSViewObjectImpl getTerminationReasonView() {
        return (IPMSViewObjectImpl) findViewObject("TerminationReasonView");
    }

    /**
     * Container's getter for ProcessStatusView.
     * @return ProcessStatusView
     */
    public IPMSViewObjectImpl getProcessStatusView() {
        return (IPMSViewObjectImpl) findViewObject("ProcessStatusView");
    }

    /**
     * Container's getter for FunctionView.
     * @return FunctionView
     */
    public FunctionViewImpl getFunctionView() {
        return (FunctionViewImpl) findViewObject("FunctionView");
    }

    /**
     * Container's getter for PriorityView.
     * @return PriorityView
     */
    public IPMSViewObjectImpl getPriorityView() {
        return (IPMSViewObjectImpl) findViewObject("PriorityView");
    }
    
    /**
    * Container's getter for SamdStatusView.
    * @return SamdStatusView
    */
    public IPMSViewObjectImpl getSamdStatusView() {
    return (IPMSViewObjectImpl) findViewObject("SamdStatusView");
    }   
        
            /**
    * Container's getter for BudgetStatusView.
    * @return BudgetStatusView
    */
    public IPMSViewObjectImpl getCollaborationTypeView() {
    return (IPMSViewObjectImpl) findViewObject("CollaborationTypeView");
    }

    /**
     * Container's getter for ProjectStateView.
     * @return ProjectStateView
     */
    public IPMSViewObjectImpl getProjectStateView() {
        return (IPMSViewObjectImpl) findViewObject("ProjectStateView");
    }

    /**
     * Container's getter for MilestoneTypeView.
     * @return MilestoneTypeView
     */
    public IPMSViewObjectImpl getMilestoneTypeView() {
        return (IPMSViewObjectImpl) findViewObject("MilestoneTypeView");
    }

    /**
     * Container's getter for ProjectAreaView.
     * @return ProjectAreaView
     */
    public ProjectAreaViewImpl getProjectAreaView() {
        return (ProjectAreaViewImpl) findViewObject("ProjectAreaView");
    }

    /**
     * Container's getter for ProjectPhaseView.
     * @return ProjectPhaseView
     */
    public IPMSViewObjectImpl getProjectPhaseView() {
        return (IPMSViewObjectImpl) findViewObject("ProjectPhaseView");
    }

    /**
     * Container's getter for ProbabilityRuleView.
     * @return ProbabilityRuleView
     */
    public IPMSViewObjectImpl getProbabilityRuleView() {
        return (IPMSViewObjectImpl) findViewObject("ProbabilityRuleView");
    }

    /**
     * Container's getter for MilestonePhaseView.
     * @return MilestonePhaseView
     */
    public IPMSViewObjectImpl getMilestonePhaseView() {
        return (IPMSViewObjectImpl) findViewObject("MilestonePhaseView");
    }


    /**
     * Container's getter for NewsCategoryView.
     * @return NewsCategoryView
     */
    public IPMSViewObjectImpl getNewsCategoryView() {
        return (IPMSViewObjectImpl) findViewObject("NewsCategoryView");
    }

    /**
     * Container's getter for EmployeeView.
     * @return EmployeeView
     */
    public IPMSViewObjectImpl getEmployeeView() {
        return (IPMSViewObjectImpl) findViewObject("EmployeeView");
    }

    /**
     * Container's getter for TeamRoleView.
     * @return TeamRoleView
     */
    public IPMSViewObjectImpl getTeamRoleView() {
        return (IPMSViewObjectImpl) findViewObject("TeamRoleView");
    }

    /**
     * Container's getter for LicenseTypeView.
     * @return LicenseTypeView
     */
    public IPMSViewObjectImpl getLicenseTypeView() {
        return (IPMSViewObjectImpl) findViewObject("LicenseTypeView");
    }

    /**
     * Container's getter for ImportStatusView.
     * @return ImportStatusView
     */
    public IPMSViewObjectImpl getImportStatusView() {
        return (IPMSViewObjectImpl) findViewObject("ImportStatusView");
    }

    /**
     * Container's getter for UserView.
     * @return UserView
     */
    public UserViewImpl getUserView() {
        return (UserViewImpl) findViewObject("UserView");
    }

    /**
     * Container's getter for DevelopmentPhaseView.
     * @return DevelopmentPhaseView
     */
    public IPMSViewObjectImpl getDevelopmentPhaseView() {
        return (IPMSViewObjectImpl) findViewObject("DevelopmentPhaseView");
    }

    /**
     * Container's getter for SubstanceView.
     * @return SubstanceView
     */
    public IPMSViewObjectImpl getSubstanceView() {
        return (IPMSViewObjectImpl) findViewObject("SubstanceView");
    }

    /**
     * Container's getter for ConfigurationView.
     * @return ConfigurationView
     */
    public ConfigurationViewImpl getConfigurationView() {
        return (ConfigurationViewImpl) findViewObject("ConfigurationView");
    }

    /**
     * Container's getter for RoleView.
     * @return RoleView
     */
    public RoleViewImpl getRoleView() {
        return (RoleViewImpl) findViewObject("RoleView");
    }

    /**
     * Container's getter for StudyStatusView.
     * @return StudyStatusView
     */
    public IPMSViewObjectImpl getStudyStatusView() {
        return (IPMSViewObjectImpl) findViewObject("StudyStatusView");
    }

    /**
     * Container's getter for AnnouncementView.
     * @return AnnouncementView
     */
    public IPMSViewObjectImpl getAnnouncementView() {
        return (IPMSViewObjectImpl) findViewObject("AnnouncementView");
    }

    /**
     * Container's getter for StrategicBusinessEntityView.
     * @return StrategicBusinessEntityView
     */
    public IPMSViewObjectImpl getStrategicBusinessEntityView() {
        return (IPMSViewObjectImpl) findViewObject("StrategicBusinessEntityView");
    }

    /**
     * Container's getter for PrefillTypeDeterministicView.
     * @return PrefillTypeDeterministicView
     */
    public IPMSViewObjectImpl getPrefillTypeDeterministicView() {
        return (IPMSViewObjectImpl) findViewObject("PrefillTypeDeterministicView");
    }


    /**
     * Container's getter for ProjectSearchStatus.
     * @return ProjectSearchStatus
     */
    public IPMSViewObjectImpl getProjectSearchStatus() {
        return (IPMSViewObjectImpl) findViewObject("ProjectSearchStatus");
    }

    /**
     * Container's getter for CostsProbabilityDefaultView.
     * @return CostsProbabilityDefaultView
     */
    public CostsProbabilityDefaultViewImpl getCostsProbabilityDefaultView() {
        return (CostsProbabilityDefaultViewImpl) findViewObject("CostsProbabilityDefaultView");
    }

    /**
     * Container's getter for ProjectSearchStatus2View.
     * @return ProjectSearchStatus2View
     */
    public IPMSViewObjectImpl getProjectSearchStatus2View() {
        return (IPMSViewObjectImpl) findViewObject("ProjectSearchStatus2View");
    }

    /**
     * Container's getter for GenericPhaseView.
     * @return GenericPhaseView
     */
    public IPMSViewObjectImpl getGenericPhaseView() {
        return (IPMSViewObjectImpl) findViewObject("GenericPhaseView");
    }

    /**
     * Container's getter for MilestoneGTView.
     * @return MilestoneGTView
     */
    public IPMSViewObjectImpl getMilestoneGTView() {
        return (IPMSViewObjectImpl) findViewObject("MilestoneGTView");
    }

    /**
     * Container's getter for PTRPhaseView.
     * @return PTRPhaseView
     */
    public IPMSViewObjectImpl getPTRPhaseView() {
        return (IPMSViewObjectImpl) findViewObject("PTRPhaseView");
    }

    /**
     * Container's getter for IpownerView.
     * @return IpownerView
     */
    public IPMSViewObjectImpl getIpownerView() {
        return (IPMSViewObjectImpl) findViewObject("IpownerView");
    }

    /**
     * Container's getter for MainGroupView.
     * @return MainGroupView
     */
    public IPMSViewObjectImpl getMainGroupView() {
        return (IPMSViewObjectImpl) findViewObject("MainGroupView");
    }

    /**
     * Container's getter for TopGroupView.
     * @return TopGroupView
     */
    public IPMSViewObjectImpl getTopGroupView() {
        return (IPMSViewObjectImpl) findViewObject("TopGroupView");
    }

    /**
     * Container's getter for TerminationReason4AreaView.
     * @return TerminationReason4AreaView
     */
    public IPMSViewObjectImpl getTerminationReason4AreaView() {
        return (IPMSViewObjectImpl) findViewObject("TerminationReason4AreaView");
    }

    public String getName() {
        return super.getName();
    }

    /**
     * Container's getter for LEProcessStatus1.
     * @return LEProcessStatus1
     */
    public IPMSViewObjectImpl getLEProcessStatus() {
        return (IPMSViewObjectImpl) findViewObject("LEProcessStatus");
    }

    /**
     * Container's getter for PrefillTypeProbabilisticView.
     * @return PrefillTypeProbabilisticView
     */
    public IPMSViewObjectImpl getPrefillTypeProbabilisticView() {
        return (IPMSViewObjectImpl)findViewObject("PrefillTypeProbabilisticView");
    }


  /**
   * Container's getter for PhaseEstimatedView1.
   * @return PhaseEstimatedView1
   */
    public IPMSViewObjectImpl getPhaseEstimatedView() {
        return (IPMSViewObjectImpl) findViewObject("PhaseEstimatedView");
    }

    /**
     * Container's getter for BaseLineTypeView1.
     * @return BaseLineTypeView1
     */
    public BaseLineTypeViewImpl getBaseLineTypeView() {
        return (BaseLineTypeViewImpl) findViewObject("BaseLineTypeView");
    }


    /**
     * Container's getter for BusinessActivitiesView1.
     * @return BusinessActivitiesView1
     */
    public IPMSViewObjectImpl getBusinessActivitiesView() {
        return (IPMSViewObjectImpl) findViewObject("BusinessActivitiesView");
    }

    /**
     * Container's getter for ResourceBundle1.
     * @return ResourceBundle1
     */
    public IPMSViewObjectImpl getResourceBundle() {
        return (IPMSViewObjectImpl) findViewObject("ResourceBundle");
    }
    
    /**
     * Container's getter for TargetClassView1.
     * @return TargetClassView1
     */
    public IPMSViewObjectImpl getTargetClassView() {
        return (IPMSViewObjectImpl) findViewObject("TargetClassView");
    }
    
    /**
     * Container's getter for TargetOriginView1.
     * @return TargetOriginView1
     */
    public IPMSViewObjectImpl getTargetOriginView() {
        return (IPMSViewObjectImpl) findViewObject("TargetOriginView");
    }

    /**
     * Container's getter for ProjectSearchStatus3View1.
     * @return ProjectSearchStatus3View1
     */
    public IPMSViewObjectImpl getProjectSearchStatus3View() {
        return (IPMSViewObjectImpl) findViewObject("ProjectSearchStatus3View");
    }

    /**
     * Container's getter for TherapeuticResearchGroup1.
     * @return TherapeuticResearchGroup1
     */
    public IPMSViewObjectImpl getTherapeuticResearchGroup() {
        return (IPMSViewObjectImpl) findViewObject("TherapeuticResearchGroup");
    }

    /**
     * Container's getter for BalStatusView1.
     * @return BalStatusView1
     */
    public IPMSViewObjectImpl getBalStatusView() {
        return (IPMSViewObjectImpl) findViewObject("BalStatusView");
    }

    /**
     * Container's getter for LtcProfitPeriod1.
     * @return LtcProfitPeriod1
     */
    public IPMSViewObjectImpl getLtcProfitPeriod() {
        return (IPMSViewObjectImpl) findViewObject("LtcProfitPeriod");
    }

    /**
     * Container's getter for ProjectDeviceTypeView1.
     * @return ProjectDeviceTypeView1
     */
    public IPMSViewObjectImpl getProjectDeviceTypeView() {
        return (IPMSViewObjectImpl) findViewObject("ProjectDeviceTypeView");
    }

    /**
     * Container's getter for RegulatoryTypeView1.
     * @return RegulatoryTypeView1
     */
    public IPMSViewObjectImpl getRegulatoryTypeView() {
        return (IPMSViewObjectImpl) findViewObject("RegulatoryTypeView");
    }

    /**
     * Container's getter for PhasePlanningTypeView1.
     * @return PhasePlanningTypeView1
     */
    public IPMSViewObjectImpl getPhasePlanningTypeView() {
        return (IPMSViewObjectImpl) findViewObject("PhasePlanningTypeView");
    }

    /**
     * Container's getter for PhaseView1.
     * @return PhaseView1
     */
    public IPMSViewObjectImpl getPhaseViewD2() {
        return (IPMSViewObjectImpl) findViewObject("PhaseViewD2");
    }

    /**
     * Container's getter for ProjectModalityView1.
     * @return ProjectModalityView1
     */
    public IPMSViewObjectImpl getProjectModalityView() {
        return (IPMSViewObjectImpl) findViewObject("ProjectModalityView");
    }

    /**
     * Container's getter for DevicePhaseView.
     * @return DevicePhaseView1
     */
    public IPMSViewObjectImpl getDevicePhaseView() {
        return (IPMSViewObjectImpl) findViewObject("DevicePhaseView");
    }

    /**
     * Container's getter for PhaseViewSAMD.
     * @return PhaseViewSAMD
     */
    public IPMSViewObjectImpl getPhaseViewSAMD() {
        return (IPMSViewObjectImpl) findViewObject("PhaseViewSAMD");
    }

    /**
     * Container's getter for LicenseDetailTypeView.
     * @return LicenseDetailTypeView
     */
    public IPMSViewObjectImpl getLicenseDetailTypeView() {
        return (IPMSViewObjectImpl) findViewObject("LicenseDetailTypeView");
    }

    /**
     * Container's getter for PartnerView.
     * @return PartnerView
     */
    public IPMSViewObjectImpl getPartnerView() {
        return (IPMSViewObjectImpl) findViewObject("PartnerView");
    }
}

