<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="WBSCategoryService"
     targetNamespace="http://xmlns.oracle.com/Primavera/P6/WS/WBSCategory/V1"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:tns="http://xmlns.oracle.com/Primavera/P6/WS/WBSCategory/V1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="WBSCategoryService">
        <plnk:role name="WBSCategoryPortType">
            <plnk:portType name="tns:WBSCategoryPortType"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/Primavera/P6/WS/WBSCategory/V1" location="../wsdl/WBSCategoryService.wsdl"/>
</wsdl:definitions>
