package com.bayer.ipms.model.views.lookups.common;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 14 12:42:00 EET 2014
// ---------------------------------------------------------------------
public interface ConfigurationViewRow extends Row {
    String getValue();

    String getCode();
}
