package com.bayer.ipms.model.views.lookups.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 18 12:15:06 EEST 2015
// ---------------------------------------------------------------------
public interface ProjectAreaViewRow extends Row {
    String getCode();

    String getIsRunningImport();
}

