prompt ---->
prompt ---->
prompt 
prompt ---->START    milestone
prompt 
prompt ---->
prompt ---->
--SET SCAN OFF;
update milestone set wbs_category=null where wbs_category is not null;
merge into milestone ooo using (select 'AS1' code,'Start of Project' name,'1' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Start of Project',ooo.is_active = '1',ooo.type_code = 'DEC' when not matched then insert (code,name,is_active,type_code) values ('AS1','Start of Project','1','DEC');
merge into milestone ooo using (select 'AS2' code,'Approval of Product Specification' name,'1' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Approval of Product Specification',ooo.is_active = '1',ooo.type_code = 'DEC' when not matched then insert (code,name,is_active,type_code) values ('AS2','Approval of Product Specification','1','DEC');
merge into milestone ooo using (select 'AS3' code,'Approval of Technical Design' name,'1' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Approval of Technical Design',ooo.is_active = '1',ooo.type_code = 'DEC' when not matched then insert (code,name,is_active,type_code) values ('AS3','Approval of Technical Design','1','DEC');
merge into milestone ooo using (select 'AS4' code,'Approval of Manufacturing Design' name,'1' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Approval of Manufacturing Design',ooo.is_active = '1',ooo.type_code = 'DEC' when not matched then insert (code,name,is_active,type_code) values ('AS4','Approval of Manufacturing Design','1','DEC');
merge into milestone ooo using (select 'AS5' code,'Approval of Product Submission' name,'1' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Approval of Product Submission',ooo.is_active = '1',ooo.type_code = 'DEC' when not matched then insert (code,name,is_active,type_code) values ('AS5','Approval of Product Submission','1','DEC');
merge into milestone ooo using (select 'AS6' code,'Completion of Design Transfer' name,'1' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Completion of Design Transfer',ooo.is_active = '1',ooo.type_code = 'DEC' when not matched then insert (code,name,is_active,type_code) values ('AS6','Completion of Design Transfer','1','DEC');
merge into milestone ooo using (select 'Compl' code,'Completion of Project' name,'1' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Completion of Project',ooo.is_active = '1',ooo.type_code = 'DEC' when not matched then insert (code,name,is_active,type_code) values ('Compl','Completion of Project','1','DEC');
merge into milestone ooo using (select 'FiM-RC' code,'Combined Tox / FiM Release Conference' name,'1' is_active,'DEV' type_code, 337 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'DMC' code,'IDMC' name,'0' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'IDMC',ooo.is_active = '0',ooo.type_code = 'DEC' when not matched then insert (code,name,is_active,type_code) values ('DMC','IDMC','0','DEC');
merge into milestone ooo using (select 'TCC' code,'TCC' name,'0' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code when not matched then insert (code,name,is_active,type_code) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code);
merge into milestone ooo using (select 'cD6' code,'cD6' name,'0' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code when not matched then insert (code,name,is_active,type_code) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code);
merge into milestone ooo using (select 'cD7' code,'cD7' name,'0' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code when not matched then insert (code,name,is_active,type_code) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code);
merge into milestone ooo using (select 'D1' code,'Start Lead Generation' name,'1' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Start Lead Generation',ooo.is_active = '1',ooo.type_code = 'DEC' when not matched then insert (code,name,is_active,type_code) values ('D1','Start Lead Generation','1','DEC');
merge into milestone ooo using (select 'D2' code,'Start Lead Optimization' name,'1' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Start Lead Optimization',ooo.is_active = '1',ooo.type_code = 'DEC' when not matched then insert (code,name,is_active,type_code) values ('D2','Start Lead Optimization','1','DEC');
merge into milestone ooo using (select 'D3' code,'Start Preclinical' name,'1' is_active,'DEC' type_code,'PCC-D4' wbs_category from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Start Preclinical',ooo.is_active = '1',ooo.type_code = 'DEC', ooo.wbs_category=nnn.wbs_category when not matched then insert (code,name,is_active,type_code,wbs_category) values ('D3','Start Preclinical','1','DEC',nnn.wbs_category);
merge into milestone ooo using (select 'PCC' code,'Preclinical Candidate' name,'1' is_active,'DEC' type_code,'PCC-D4' wbs_category, 105 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.wbs_category=nnn.wbs_category, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,wbs_category,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.wbs_category,nnn.ordering);
merge into milestone ooo using (select 'D4' code,'Phase I Decision' name,'1' is_active,'DEC' type_code,'D4-D6' wbs_category from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Phase I Decision',ooo.is_active = '1',ooo.type_code = 'DEC', ooo.wbs_category=nnn.wbs_category when not matched then insert (code,name,is_active,type_code,wbs_category) values ('D4','Phase I Decision','1','DEC',nnn.wbs_category);
merge into milestone ooo using (select 'D5' code,'Phase IIa Decision' name,'1' is_active,'DEC' type_code,'D4-D6' wbs_category from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.wbs_category=nnn.wbs_category when not matched then insert (code,name,is_active,type_code,wbs_category) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.wbs_category);
merge into milestone ooo using (select 'D6' code,'Phase IIb Decision' name,'1' is_active,'DEC' type_code,'D6-D7' wbs_category from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Phase IIb Decision',ooo.is_active = '1',ooo.type_code = 'DEC', ooo.wbs_category=nnn.wbs_category when not matched then insert (code,name,is_active,type_code,wbs_category) values ('D6','Phase IIb Decision','1','DEC',nnn.wbs_category);
merge into milestone ooo using (select 'D7' code,'Phase III Decision' name,'1' is_active,'DEC' type_code,'D7-D8' wbs_category from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Phase III Decision',ooo.is_active = '1',ooo.type_code = 'DEC', ooo.wbs_category=nnn.wbs_category when not matched then insert (code,name,is_active,type_code,wbs_category) values ('D7','Phase III Decision','1','DEC',nnn.wbs_category);
merge into milestone ooo using (select 'D8' code,'Release for Submission' name,'1' is_active,'DEC' type_code,'D8-Launch' wbs_category from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Release for Submission',ooo.is_active = '1',ooo.type_code = 'DEC', ooo.wbs_category=nnn.wbs_category when not matched then insert (code,name,is_active,type_code,wbs_category) values ('D8','Release for Submission','1','DEC',nnn.wbs_category);
merge into milestone ooo using (select 'D9' code,'Start Launch' name,'1' is_active,'DEC' type_code,'Launch' wbs_category from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Start Launch',ooo.is_active = '1',ooo.type_code = 'DEC', ooo.wbs_category=nnn.wbs_category when not matched then insert (code,name,is_active,type_code,wbs_category) values ('D9','Start Launch','1','DEC',nnn.wbs_category);
merge into milestone ooo using (select 'M4A' code,'Submission for Clinical Trial' name,'1' is_active,'DEV' type_code, 340 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'M4B' code,'FPFV Phase I' name,'1' is_active,'DEV' type_code, 350 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'M4C' code,'FPFV Phase IIa' name,'1' is_active,'DEV' type_code, 360 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'M5A' code,'M5A (Start of PoT study (FPFV))' name,'0' is_active,'DEV' type_code, 370 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'M5B' code,'LPLV Phase IIa' name,'1' is_active,'DEV' type_code, 380 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'M6A' code,'FPFV Phase IIb' name,'1' is_active,'DEV' type_code, 390 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'M6B' code,'LPLV Phase IIb' name,'1' is_active,'DEV' type_code, 410 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'M6P' code,'Primary Completion Phase IIb' name,'1' is_active,'DEV' type_code, 1 is_lead_study_relevant, 400 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.is_lead_study_relevant=nnn.is_lead_study_relevant, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,is_lead_study_relevant,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.is_lead_study_relevant,nnn.ordering);
merge into milestone ooo using (select 'M7A' code,'FPFV Phase III' name,'1' is_active,'DEV' type_code, 420 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'M7B' code,'LPFV Phase III' name,'1' is_active,'DEV' type_code, 430 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'M7C' code,'LPLV Phase III' name,'1' is_active,'DEV' type_code, 450 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'M7P' code,'Primary Completion Phase III' name,'1' is_active,'DEV' type_code, 1 is_lead_study_relevant, 440 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.is_lead_study_relevant=nnn.is_lead_study_relevant, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,is_lead_study_relevant,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.is_lead_study_relevant,nnn.ordering);
merge into milestone ooo using (select 'M8A' code,'First Submission' name,'1' is_active,'DEV' type_code, 460 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'M8B' code,'First Approval' name,'1' is_active,'DEV' type_code, 470 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'M9' code,'First Launch' name,'1' is_active,'DEV' type_code, 480 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'postD9' code,'post D9 (Marketing Phase)' name,'1' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'post D9 (Marketing Phase)',ooo.is_active = '1',ooo.type_code = 'DEC' when not matched then insert (code,name,is_active,type_code) values ('postD9','post D9 (Marketing Phase)','1','DEC');
merge into milestone ooo using (select 'PoC' code,'Proof of Concept' name,'1' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Proof of Concept',ooo.is_active = '1',ooo.type_code = 'DEC' when not matched then insert (code,name,is_active,type_code) values ('PoC','Proof of Concept','1','DEC');
merge into milestone ooo using (select 'Termn' code,'Termination of Project' name,'1' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Termination of Project',ooo.is_active = '1',ooo.type_code = 'DEC' when not matched then insert (code,name,is_active,type_code) values ('Termn','Termination of Project','1','DEC');
merge into milestone ooo using (select '1-APR' code,'Approval EU' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Approval EU',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('1-APR','Approval EU','1','REG');
merge into milestone ooo using (select '1GLP' code,'1st GLP tox' name,'1' is_active,'DEV' type_code, 335 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select '1-LAU' code,'Launch EU' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Launch EU',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('1-LAU','Launch EU','1','REG');
merge into milestone ooo using (select '1-SUB' code,'Submission EU' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Submission EU',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('1-SUB','Submission EU','1','REG');
merge into milestone ooo using (select '2-APR' code,'Approval US' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Approval US',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('2-APR','Approval US','1','REG');
merge into milestone ooo using (select '2-LAU' code,'Launch US' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Launch US',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('2-LAU','Launch US','1','REG');
merge into milestone ooo using (select '2-SUB' code,'Submission US' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Submission US',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('2-SUB','Submission US','1','REG');
merge into milestone ooo using (select '3-APR' code,'Approval J' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Approval J',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('3-APR','Approval J','1','REG');
merge into milestone ooo using (select '3-LAU' code,'Launch J' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Launch J',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('3-LAU','Launch J','1','REG');
merge into milestone ooo using (select '3-SUB' code,'Submission J' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Submission J',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('3-SUB','Submission J','1','REG');
merge into milestone ooo using (select '4-APR' code,'Approval LA' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Approval LA',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('4-APR','Approval LA','1','REG');
merge into milestone ooo using (select '4-LAU' code,'Launch LA' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Launch LA',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('4-LAU','Launch LA','1','REG');
merge into milestone ooo using (select '4-SUB' code,'Submission LA' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Submission LA',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('4-SUB','Submission LA','1','REG');
merge into milestone ooo using (select '5-APR' code,'Approval AP' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Approval AP',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('5-APR','Approval AP','1','REG');
merge into milestone ooo using (select '5-LAU' code,'Launch AP' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Launch AP',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('5-LAU','Launch AP','1','REG');
merge into milestone ooo using (select '5-SUB' code,'Submission AP' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Submission AP',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('5-SUB','Submission AP','1','REG');
merge into milestone ooo using (select '6-APR' code,'Approval CN' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Approval CN',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('6-APR','Approval CN','1','REG');
merge into milestone ooo using (select '6-LAU' code,'Launch CN' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Launch CN',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('6-LAU','Launch CN','1','REG');
merge into milestone ooo using (select '6-SUB' code,'Submission CN' name,'1' is_active,'REG' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Submission CN',ooo.is_active = '1',ooo.type_code = 'REG' when not matched then insert (code,name,is_active,type_code) values ('6-SUB','Submission CN','1','REG');
merge into milestone ooo using (select 'CSM' code,'Candidate Selection Meeting' name,'1' is_active,'DEV' type_code, 310 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'eD3' code,'Endorsement D3' name,'1' is_active,'DEV' type_code, 320 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'D4E' code,'D4E' name,'1' is_active,'DEV' type_code, 330 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'cPoT' code,'Controlling PoT' name,'1' is_active,'DEC' type_code from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = 'Controlling PoT',ooo.is_active = '1',ooo.type_code = 'DEC' when not matched then insert (code,name,is_active,type_code) values ('cPoT','Controlling PoT','1','DEC');
merge into milestone ooo using (select 'eD2' code,'Endorsement D2' name,'1' is_active,'DEV' type_code, 300 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'HTS' code,'HTS' name,'1' is_active,'DEV' type_code, 280 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
merge into milestone ooo using (select 'LSA' code,'LSA' name,'1' is_active,'DEV' type_code, 290 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
update milestone set is_active = '0' where code = 'PoT' and is_active != '0';
update milestone set wbs_category='PCC-D4' where code='1GLP';
update milestone set wbs_category='D4-D6' where code='M4B';
update milestone set wbs_category='D6-D7' where code='M6A';
update milestone set wbs_category='D7-D8' where code='M7A';
update milestone set wbs_category='D8-Launch' where code='M8A';
update milestone set wbs_category='Launch' where code='M9';
merge into milestone ooo using (select 'MPoC' code,'Proof of Concept' name,'1' is_active,'DEV' type_code, 385 ordering from dual) nnn on (ooo.code=nnn.code) when matched then update set ooo.name = nnn.name,ooo.is_active = nnn.is_active,ooo.type_code = nnn.type_code, ooo.ordering=nnn.ordering when not matched then insert (code,name,is_active,type_code,ordering) values (nnn.code,nnn.name,nnn.is_active,nnn.type_code,nnn.ordering);
commit;
prompt ---->END    milestone
prompt ---->
prompt ---->

/
prompt ---->START    milestone
prompt 
prompt ---->
prompt ---->
SET SCAN OFF;
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS0', 'MS0', 'DEC-SAMD', '1', '680');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS1', 'MS1', 'DEC-SAMD', '1', '690');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS2', 'MS2', 'DEC-SAMD', '1', '700');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3a', 'MS3a', 'DEC-SAMD', '1', '710');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3b', 'MS3b', 'DEC-SAMD', '1', '720');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3c', 'MS3c', 'DEC-SAMD', '1', '730');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3d', 'MS3d', 'DEC-SAMD', '1', '740');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3e', 'MS3e', 'DEC-SAMD', '1', '750');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3f', 'MS3f', 'DEC-SAMD', '1', '760');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3g', 'MS3g', 'DEC-SAMD', '1', '770');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3h', 'MS3h', 'DEC-SAMD', '1', '780');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3i', 'MS3i', 'DEC-SAMD', '1', '790');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3j', 'MS3j', 'DEC-SAMD', '1', '800');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3k', 'MS3k', 'DEC-SAMD', '1', '810');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3m', 'MS3m', 'DEC-SAMD', '1', '820');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3n', 'MS3n', 'DEC-SAMD', '1', '830');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3o', 'MS3o', 'DEC-SAMD', '1', '840');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3p', 'MS3p', 'DEC-SAMD', '1', '850');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3q', 'MS3q', 'DEC-SAMD', '1', '860');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3r', 'MS3r', 'DEC-SAMD', '1', '870');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3s', 'MS3s', 'DEC-SAMD', '1', '880');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3t', 'MS3t', 'DEC-SAMD', '1', '890');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3u', 'MS3u', 'DEC-SAMD', '1', '900');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3v', 'MS3v', 'DEC-SAMD', '1', '910');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3w', 'MS3w', 'DEC-SAMD', '1', '920');
INSERT INTO IPMS_DATA.MILESTONE (CODE, NAME, TYPE_CODE, IS_ACTIVE, ORDERING) VALUES ('MS3x', 'MS3x', 'DEC-SAMD', '1', '930');

commit;
prompt ---->END    milestone
prompt ---->
prompt ---->