package com.bayer.ipms.model.views.imports.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 04 18:06:27 EET 2014
// ---------------------------------------------------------------------
public interface ImportTimelineView extends ViewObject {
    void setFailedVar(String value);

    void setStatusVar(String value);

    void setStudyRelatedVar(String value);

    void setStudyVar(String value);
}
