package com.bayer.ipms.model.views.lookups.client;

import com.bayer.ipms.model.views.lookups.common.SubFunctionViewRow;

import oracle.jbo.RowSet;
import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 09 13:58:16 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SubFunctionViewRowClient extends RowImpl implements SubFunctionViewRow {
    /**
     * This is the default constructor (do not remove).
     */
    public SubFunctionViewRowClient() {
    }

    public RowSet getFunctionView() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getFunctionView",null,null);
        return (RowSet)_ret;
    }
}
