<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns1="http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://xmlns.bayer.com/ipms/soa" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns1 ns0 mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://xmlns.bayer.com/ipms"
                xmlns:intgfault="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns3="http://xmlns.bayer.com/ipms/qplan"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/DeleteStudy.wsdl"/>
            <oracle-xsl-mapper:rootElement name="delete" namespace="http://xmlns.bayer.com/ipms/soa"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../wsdl/WBSService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ReadWBSResponse" namespace="http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2"/>
            <oracle-xsl-mapper:param name="ReadWBSAfterOut.result"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/DeleteStudy.wsdl"/>
            <oracle-xsl-mapper:rootElement name="response" namespace="http://xmlns.bayer.com/ipms/soa"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU JUL 14 10:19:53 CEST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="ReadWBSAfterOut.result"/>
   <xsl:template match="/">
      <ns0:response>
         <ns0:complete>
            <ns2:wbsNodes>
              <xsl:for-each select="/ns0:delete/ns2:wbsNodes/ns2:wbs">
                <xsl:if test='current()/@id!=""'>
                  <xsl:choose>
                    <xsl:when test='$ReadWBSAfterOut.result/ns1:ReadWBSResponse/ns1:WBS/ns1:ObjectId = current()/@id'>
                      <ns2:wbs timelineId="{@timelineId}" id="{@id}" responseStatus="Error">
                        <ns2:code>
                           <xsl:value-of select="ns2:code"/>
                        </ns2:code>
                        <ns2:name>
                           <xsl:value-of select="ns2:name"/>
                        </ns2:name>
                        <ns2:studyPhase>
                           <xsl:value-of select="ns2:studyPhase"/>
                        </ns2:studyPhase>
                     </ns2:wbs>
                    </xsl:when>
                    <xsl:otherwise>
                      <ns2:wbs timelineId="{@timelineId}" id="{@id}"  responseStatus="Deleted">
                        <ns2:code>
                           <xsl:value-of select="ns2:code"/>
                        </ns2:code>
                        <ns2:name>
                           <xsl:value-of select="ns2:name"/>
                        </ns2:name>
                        <ns2:studyPhase>
                           <xsl:value-of select="ns2:studyPhase"/>
                        </ns2:studyPhase>
                     </ns2:wbs>
                    </xsl:otherwise>
                  </xsl:choose>
                </xsl:if>
              </xsl:for-each>
            </ns2:wbsNodes>
         </ns0:complete>
      </ns0:response>
   </xsl:template>
</xsl:stylesheet>
