<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="http://xmlns.bayer.com/ipms/soa" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns1="http://xmlns.oracle.com/Primavera/P6/WS/BaselineProject/V2"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 ns1 xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:intgfault="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1"
                xmlns:ns3="http://xmlns.bayer.com/ipms/qplan"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://xmlns.bayer.com/ipms"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://xmlns.oracle.com/ipms_mw/ipms_soa/DeleteBaselines"
                xmlns:ns4="http://xmlns.bayer.com/ipms/cache">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DeleteBaselines.wsdl"/>
        <oracle-xsl-mapper:rootElement name="delete" namespace="http://xmlns.bayer.com/ipms/soa"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../wsdl/BaselineProjectService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ReadBaselineProjectsResponse"
                                       namespace="http://xmlns.oracle.com/Primavera/P6/WS/BaselineProject/V2"/>
        <oracle-xsl-mapper:param name="ReadBaselineProjects_Out.result"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../wsdl/BaselineProjectService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="DeleteBaselineProjects"
                                       namespace="http://xmlns.oracle.com/Primavera/P6/WS/BaselineProject/V2"/>
        <oracle-xsl-mapper:param name="DeleteBaselineProjects_In.params"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/DeleteBaselines.wsdl"/>
        <oracle-xsl-mapper:rootElement name="response" namespace="http://xmlns.bayer.com/ipms/soa"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU OCT 22 15:36:57 EEST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="ReadBaselineProjects_Out.result"/>
  <xsl:param name="DeleteBaselineProjects_In.params"/>
  <xsl:template match="/">
    <ns0:response id="{/ns0:delete/@id}">
      <ns0:complete id="{/ns0:delete/@id}">
        <ns2:baselines timelineId="{/ns0:delete/ns2:baselines/@timelineId}">
          <xsl:for-each select="$ReadBaselineProjects_Out.result/ns1:ReadBaselineProjectsResponse/ns1:BaselineProject[ns1:ObjectId=$DeleteBaselineProjects_In.params/ns1:DeleteBaselineProjects/ns1:ObjectId]">
            <ns2:baseline id="{ns1:ObjectId}">
              <ns2:name>
                <xsl:value-of select="ns1:Name"/>
              </ns2:name>
              <ns2:baselineTypeObjectId>
                <xsl:value-of select="ns1:BaselineTypeObjectId"/>
              </ns2:baselineTypeObjectId>
              <ns2:createDate>
                <xsl:value-of select="ns1:CreateDate"/>
              </ns2:createDate>
              <ns2:description>
                <xsl:value-of select="ns1:Description"/>
              </ns2:description>
            </ns2:baseline>
          </xsl:for-each>
        </ns2:baselines>
      </ns0:complete>
    </ns0:response>
  </xsl:template>
</xsl:stylesheet>
