<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:P6="http://xmlns.oracle.com/Primavera/P6/WS/BaselineProject/V2"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl P6 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:intgfault="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../wsdl/BaselineProjectService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ReadBaselineProjectsResponse"
                                       namespace="http://xmlns.oracle.com/Primavera/P6/WS/BaselineProject/V2"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../wsdl/BaselineProjectService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="DeleteBaselineProjects"
                                       namespace="http://xmlns.oracle.com/Primavera/P6/WS/BaselineProject/V2"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED OCT 21 19:15:24 EEST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <P6:DeleteBaselineProjects>
      <!-- We assume that BaselineProjects are sorted by CreateDate DESC -->
      <xsl:for-each select="/P6:ReadBaselineProjectsResponse/P6:BaselineProject">
        <xsl:variable name="currDate" select="xp20:current-dateTime()"/>
        <xsl:variable name="monthsBetween"
                      select="(xp20:year-from-dateTime($currDate) - xp20:year-from-dateTime(P6:CreateDate)) * 12 + (xp20:month-from-dateTime($currDate) - xp20:month-from-dateTime(P6:CreateDate))"/>
        <xsl:variable name="format"
                      select="concat(substring('[Y0001]M[M01]', 1, number($monthsBetween>12) * 13), substring('[Y0001]W[W01]', 1, number(not($monthsBetween>12)) * 13))"/>
        <xsl:if test="position() > 1 and xp20:format-dateTime(P6:CreateDate, $format)=xp20:format-dateTime(preceding-sibling::P6:BaselineProject[1]/P6:CreateDate, $format)">
          <P6:ObjectId>
            <xsl:value-of select="P6:ObjectId"/>
          </P6:ObjectId>
        </xsl:if>
      </xsl:for-each>
    </P6:DeleteBaselineProjects>
  </xsl:template>
</xsl:stylesheet>
