<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns2="http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns1="http://xmlns.bayer.com/ipms/soa" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://xmlns.bayer.com/ipms" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/Primavera/P6/WS/BaselineProject/V2"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns2 ns1 ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:intgfault="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1"
                xmlns:ns4="http://xmlns.bayer.com/ipms/cache" xmlns:ns5="http://xmlns.bayer.com/ipms/qplan"
                xmlns:ns3="http://xmlns.oracle.com/Primavera/P6/V18.8.4/API/BusinessObjects"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../wsdl/BaselineProjectService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ReadBaselineProjectsResponse"
                                       namespace="http://xmlns.oracle.com/Primavera/P6/WS/BaselineProject/V2"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../ReadTimeline.wsdl"/>
        <oracle-xsl-mapper:rootElement name="read" namespace="http://xmlns.bayer.com/ipms/soa"/>
        <oracle-xsl-mapper:param name="inputVariable.payload"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/com/oracle/xmlns/Primavera/P6/WS/UDFValue/V1/UDFValueService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ReadUDFValuesResponse"
                                       namespace="http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1"/>
        <oracle-xsl-mapper:param name="ReadLtcIdUDFOut.result"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../ReadTimeline.wsdl"/>
        <oracle-xsl-mapper:rootElement name="baselines" namespace="http://xmlns.bayer.com/ipms"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED MAR 02 22:20:54 CET 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="inputVariable.payload"/>
  <xsl:param name="ReadLtcIdUDFOut.result"/>
  <xsl:template match="/">
    <tns:baselines timelineId="{$inputVariable.payload/ns1:read/tns:timeline/@id}">
      <xsl:for-each select="/ns0:ReadBaselineProjectsResponse/ns0:BaselineProject">
        <xsl:variable name="ObjectId" select="ns0:ObjectId"/>
        <tns:baseline id="{ns0:ObjectId}">
          <tns:name>
            <xsl:value-of select="ns0:Name"/>
          </tns:name>
          <tns:baselineTypeObjectId>
            <xsl:value-of select="ns0:BaselineTypeObjectId"/>
          </tns:baselineTypeObjectId>
          <tns:createDate>
            <xsl:value-of select="ns0:CreateDate"/>
          </tns:createDate>
          <tns:description>
            <xsl:value-of select="ns0:Description"/>
          </tns:description>
          <tns:ltcId>
            <xsl:value-of select="$ReadLtcIdUDFOut.result/ns2:ReadUDFValuesResponse/ns2:UDFValue[ns2:ForeignObjectId=$ObjectId]/ns2:Text"/>
          </tns:ltcId>
        </tns:baseline>
      </xsl:for-each>
    </tns:baselines>
  </xsl:template>
</xsl:stylesheet>
