<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns2="http://xmlns.bayer.com/ipms/cache" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:intgfault="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:p6a="http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1" xmlns:p6ca="http://xmlns.oracle.com/Primavera/P6/WS/CostAccount/V1" xmlns:p6ec="http://xmlns.oracle.com/Primavera/P6/WS/ExpenseCategory/V1" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns3="http://xmlns.bayer.com/ipms/qplan" xmlns:ipms-soa="http://xmlns.bayer.com/ipms/soa" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ipms="http://xmlns.bayer.com/ipms" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:tns="http://xmlns.oracle.com/Primavera/P6/WS/ActivityExpense/V1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns2 plnk soap wsdl intgfault p6a p6ca p6ec ns3 ipms-soa ipms xsd tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../UpdateTimeline.wsdl"/>
            <oracle-xsl-mapper:rootElement name="update" namespace="http://xmlns.bayer.com/ipms/soa"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../wsdl/ActivityService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ReadActivitiesResponse" namespace="http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1"/>
            <oracle-xsl-mapper:param name="ReadActivities_Out.result"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../wsdl/CostAccountService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ReadCostAccountsResponse" namespace="http://xmlns.oracle.com/Primavera/P6/WS/CostAccount/V1"/>
            <oracle-xsl-mapper:param name="ReadCostAccounts_Out.result"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../wsdl/ExpenseCategoryService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ReadExpenseCategoriesResponse" namespace="http://xmlns.oracle.com/Primavera/P6/WS/ExpenseCategory/V1"/>
            <oracle-xsl-mapper:param name="ReadExpenseCategories_Out.result"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../wsdl/ActivityExpenseService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CreateActivityExpenses" namespace="http://xmlns.oracle.com/Primavera/P6/WS/ActivityExpense/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON JUN 01 10:43:33 CEST 2015].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="ReadActivities_Out.result"/>
  <xsl:param name="ReadCostAccounts_Out.result"/>
  <xsl:param name="ReadExpenseCategories_Out.result"/>
  <xsl:template match="/">
    <tns:CreateActivityExpenses>
      <xsl:for-each select="/ipms-soa:update/ipms:timeline/ipms:expenses/ipms:expense">
        <tns:ActivityExpense>
            <tns:ExpenseItem>
                <xsl:value-of select="concat(ipms:functionCode, ' ', ipms:costType)"/>
            </tns:ExpenseItem>
            <tns:ActivityObjectId>
                <xsl:value-of select="$ReadActivities_Out.result/p6a:ReadActivitiesResponse/p6a:Activity[p6a:WBSObjectId=current()/@wbsId][1]/p6a:ObjectId"/>
            </tns:ActivityObjectId>
            <tns:CostAccountObjectId>
                  <xsl:value-of select="$ReadCostAccounts_Out.result/p6ca:ReadCostAccountsResponse/p6ca:CostAccount[p6ca:Id=current()/ipms:functionCode]/p6ca:ObjectId"/>
            </tns:CostAccountObjectId>
            <tns:ExpenseCategoryObjectId>
                <xsl:value-of select="$ReadExpenseCategories_Out.result/p6ec:ReadExpenseCategoriesResponse/p6ec:ExpenseCategory[p6ec:Name=current()/ipms:costType]/p6ec:ObjectId"/>
            </tns:ExpenseCategoryObjectId>
            <tns:PlannedCost>
                <xsl:value-of select="ipms:planCost"/>
            </tns:PlannedCost>
        </tns:ActivityExpense>
      </xsl:for-each>
    </tns:CreateActivityExpenses>
  </xsl:template>
</xsl:stylesheet>