<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:tns="http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ipms-soa="http://xmlns.bayer.com/ipms/soa" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:p6ae="http://xmlns.oracle.com/Primavera/P6/WS/ActivityExpense/V1"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ipms-soa p6ae tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:intgfault="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1"
                xmlns:ns1="http://xmlns.bayer.com/ipms/cache" xmlns:ns4="http://xmlns.bayer.com/ipms/qplan"
                xmlns:ipms="http://xmlns.bayer.com/ipms"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../UpdateTimeline.wsdl"/>
        <oracle-xsl-mapper:rootElement name="update" namespace="http://xmlns.bayer.com/ipms/soa"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../UpdateTimeline.wsdl"/>
        <oracle-xsl-mapper:rootElement name="config" namespace="http://xmlns.bayer.com/ipms/soa"/>
        <oracle-xsl-mapper:param name="ReadConfigurationOut.payload"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../wsdl/ActivityExpenseService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CreateActivityExpenses"
                                       namespace="http://xmlns.oracle.com/Primavera/P6/WS/ActivityExpense/V1"/>
        <oracle-xsl-mapper:param name="CreateActivityExpenses_In.params"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../wsdl/ActivityExpenseService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CreateActivityExpensesResponse"
                                       namespace="http://xmlns.oracle.com/Primavera/P6/WS/ActivityExpense/V1"/>
        <oracle-xsl-mapper:param name="CreateActivityExpenses_Out.result"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/com/oracle/xmlns/Primavera/P6/WS/UDFValue/V1/UDFValueService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CreateUDFValues"
                                       namespace="http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU JUN 11 15:01:03 EEST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="ReadConfigurationOut.payload"/>
  <xsl:param name="CreateActivityExpenses_In.params"/>
  <xsl:param name="CreateActivityExpenses_Out.result"/>
  <xsl:template match="/">
    <tns:CreateUDFValues>
      <xsl:for-each select="/ipms-soa:update/ipms:timeline/ipms:expenses/ipms:expense">
        <xsl:if test="ipms:comments/node()">
          <!-- I assume that CreateActivityExpenses returns ObjectIds in the same order as ExpenseItems were sent -->
          <xsl:variable name="expensePos" select="position()"/>
          <tns:UDFValue>
            <tns:ForeignObjectId>
              <xsl:value-of select="$CreateActivityExpenses_Out.result/p6ae:CreateActivityExpensesResponse/p6ae:ObjectId[$expensePos]"/>
            </tns:ForeignObjectId>
            <tns:Text>
              <xsl:value-of select="ipms:comments"/>
            </tns:Text>
            <tns:UDFTypeObjectId>
              <xsl:value-of select="$ReadConfigurationOut.payload/ipms-soa:config/ipms-soa:activity/ipms-soa:expenseCommentTypeId"/>
            </tns:UDFTypeObjectId>
          </tns:UDFValue>
        </xsl:if>
      </xsl:for-each>
    </tns:CreateUDFValues>
  </xsl:template>
</xsl:stylesheet>
