<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns2="http://xmlns.bayer.com/ipms/cache" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:intgfault="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:tns="http://xmlns.oracle.com/Primavera/P6/WS/CostAccount/V1" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns3="http://xmlns.bayer.com/ipms/qplan" xmlns:ipms-soa="http://xmlns.bayer.com/ipms/soa" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ipms="http://xmlns.bayer.com/ipms" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns2 soap wsdl intgfault tns ns3 ipms-soa plnk ipms xsd xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../UpdateFunctions.wsdl"/>
            <oracle-xsl-mapper:rootElement name="update" namespace="http://xmlns.bayer.com/ipms/soa"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../wsdl/CostAccountService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ReadCostAccountsResponse" namespace="http://xmlns.oracle.com/Primavera/P6/WS/CostAccount/V1"/>
            <oracle-xsl-mapper:param name="ReadCostAccounts_Out.result"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../wsdl/CostAccountService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CreateCostAccounts" namespace="http://xmlns.oracle.com/Primavera/P6/WS/CostAccount/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON JUN 01 10:43:33 CEST 2015].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="ReadCostAccounts_Out.result"/>
  <xsl:template match="/">
      <xsl:variable name="costAccountActive" select="$ReadCostAccounts_Out.result/tns:ReadCostAccountsResponse/tns:CostAccount[tns:Id = 'ACTIVE']"/>
      <xsl:variable name="costAccountInactive" select="$ReadCostAccounts_Out.result/tns:ReadCostAccountsResponse/tns:CostAccount[tns:Id = 'INACTIVE']"/>
    <tns:CreateCostAccounts>
      <xsl:for-each select="/ipms-soa:update/ipms:functions/ipms:function">
      <xsl:if test="empty($ReadCostAccounts_Out.result/tns:ReadCostAccountsResponse/tns:CostAccount[tns:Id=current()/ipms:code])">
        <tns:CostAccount>
          <tns:Id>
            <xsl:value-of select="ipms:code"/>
          </tns:Id>
          <tns:Name>
            <xsl:value-of select="ipms:name"/>
          </tns:Name>
          <tns:ParentObjectId>
            <xsl:choose>
              <xsl:when test="@disabled='false'">
                <xsl:value-of select="$costAccountActive/tns:ObjectId"/>
              </xsl:when>
              <xsl:otherwise>
                <xsl:value-of select="$costAccountInactive/tns:ObjectId"/>
              </xsl:otherwise>
            </xsl:choose>
          </tns:ParentObjectId>
        </tns:CostAccount>
      </xsl:if>
      </xsl:for-each>
    </tns:CreateCostAccounts>
  </xsl:template>
</xsl:stylesheet>