create or replace view baseline_wbs_vw as
select
	tl.id baseline_id,
	null project_id,
	tl.timeline_id,
	'BSL' as timeline_type_code,
	xt.wbs_id,
	xt.parent_wbs_id,
	xt.study_id,
	xt.code,
	xt.name,
	get_date(xt.start_date_str) as start_date,
	get_date(xt.finish_date_str) as finish_date,
	xt.study_phase,
	xt.sequence_number,
	decode(xt.placeholder, 'true', 1, 0) as placeholder,
	--nvl(st.is_obligation,0) as is_obligation,
	--nvl(st.is_probing,0) as is_probing,
	--nvl(st.is_gpdc_approved,0) as is_gpdc_approved,
	xt.plan_patients,
	xt.actual_patients,
	--st.int_ext_flag,
	--st.study_modus_no,
	--st.study_modus_name,
	--st.clin_plan_type,
	xt.study_unit_count,
	xt.study_unit_count_plan,
	--st.therapeutic_group_code,
	--st.therapeutic_group_desc,
	--st.is_timeline_auto_import,
	--st.volunteer_flag,
	xt.study_country_count,
	xt.study_country_count_plan,
	--st.subject_type,
	xt.plan_entered_screen,
	xt.act_entered_screen,
	--st.is_lead,
	xt.fte_avg
from
	timeline_baseline tl,
	xmltable(
		xmlnamespaces(default 'http://xmlns.bayer.com/ipms'),
		'/baseline/wbsNodes/wbs' passing tl.details
		columns
			wbs_id path '/wbs/@id',
			parent_wbs_id path '/wbs/@parentId',
			study_id path '/wbs/@studyId',
			code path '/wbs/code',
			name path '/wbs/name',
			start_date_str path '/wbs/startDate',
			finish_date_str path '/wbs/finishDate',
			study_phase path '/wbs/studyPhase',
			sequence_number path '/wbs/sequenceNumber',
			placeholder path '/wbs/@placeholder',
			plan_patients path '/wbs/planPatients',
			actual_patients path '/wbs/actualPatients',
			plan_entered_screen path '/wbs/planEnteredScreen',
			act_entered_screen path '/wbs/actEnteredScreen',
			study_country_count_plan path '/wbs/studyCountryCountPlan',
			study_country_count path '/wbs/studyCountryCount',
			study_unit_count path '/wbs/studyUnitCount',
			study_unit_count_plan path '/wbs/studyUnitCountPlan',
			fte_avg path '/wbs/FTEAvg'
	) xt
where tl.details is not null;