package com.bayer.ipms.model.views.imports;

import com.bayer.ipms.model.base.IPMSEntityImpl;
import com.bayer.ipms.model.base.IPMSViewRowImpl;

import com.bayer.ipms.model.views.imports.common.ImportStudyDataViewRow;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 26 18:14:59 EET 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImportStudyDataViewRowImpl extends IPMSViewRowImpl implements ImportStudyDataViewRow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ImportId {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getImportId();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setImportId((String)value);
            }
        }
        ,
        ProjectId {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getProjectId();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setProjectId((String)value);
            }
        }
        ,
        StudyId {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getStudyId();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setStudyId((String)value);
            }
        }
        ,
        WbsId {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getWbsId();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setWbsId((String)value);
            }
        }
        ,
        Name {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getName();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setName((String)value);
            }
        }
        ,
        StartDate {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getStartDate();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setStartDate((Date)value);
            }
        }
        ,
        FinishDate {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getFinishDate();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setFinishDate((Date)value);
            }
        }
        ,
        Placeholder {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getPlaceholder();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setPlaceholder((BigDecimal)value);
            }
        }
        ,
        StatusCode {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getStatusCode();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setStatusCode((String)value);
            }
        }
        ,
        StatusDescription {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getStatusDescription();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setStatusDescription((String)value);
            }
        }
        ,
        CreateDate {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getCreateDate();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setCreateDate((Date)value);
            }
        }
        ,
        StatusName {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getStatusName();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setStatusName((String)value);
            }
        }
        ,
        ActionName {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getActionName();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setActionName((String)value);
            }
        }
        ,
        ActionCode {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getActionCode();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setActionCode((String)value);
            }
        }
        ,
        Code {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getCode();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setCode((String)value);
            }
        }
        ,
        OldFinishDate {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getOldFinishDate();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setOldFinishDate((Date)value);
            }
        }
        ,
        OldStartDate {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getOldStartDate();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setOldStartDate((Date)value);
            }
        }
        ,
        IsExisting {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getIsExisting();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setIsExisting((Boolean)value);
            }
        }
        ,
        ImportActionView {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getImportActionView();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ImportStatusView {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getImportStatusView();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ImportActionView1 {
            public Object get(ImportStudyDataViewRowImpl obj) {
                return obj.getImportActionView1();
            }

            public void put(ImportStudyDataViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ImportStudyDataViewRowImpl object);

        public abstract void put(ImportStudyDataViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IMPORTID = AttributesEnum.ImportId.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int STUDYID = AttributesEnum.StudyId.index();
    public static final int WBSID = AttributesEnum.WbsId.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int FINISHDATE = AttributesEnum.FinishDate.index();
    public static final int PLACEHOLDER = AttributesEnum.Placeholder.index();
    public static final int STATUSCODE = AttributesEnum.StatusCode.index();
    public static final int STATUSDESCRIPTION = AttributesEnum.StatusDescription.index();
    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int STATUSNAME = AttributesEnum.StatusName.index();
    public static final int ACTIONNAME = AttributesEnum.ActionName.index();
    public static final int ACTIONCODE = AttributesEnum.ActionCode.index();
    public static final int CODE = AttributesEnum.Code.index();
    public static final int OLDFINISHDATE = AttributesEnum.OldFinishDate.index();
    public static final int OLDSTARTDATE = AttributesEnum.OldStartDate.index();
    public static final int ISEXISTING = AttributesEnum.IsExisting.index();
    public static final int IMPORTACTIONVIEW = AttributesEnum.ImportActionView.index();
    public static final int IMPORTSTATUSVIEW = AttributesEnum.ImportStatusView.index();
    public static final int IMPORTACTIONVIEW1 = AttributesEnum.ImportActionView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ImportStudyDataViewRowImpl() {
    }

    /**
     * Gets ImportStudyData entity object.
     * @return the ImportStudyData
     */
    public IPMSEntityImpl getImportStudyData() {
        return (IPMSEntityImpl)getEntity(0);
    }

    /**
     * Gets ImportStatus entity object.
     * @return the ImportStatus
     */
    public IPMSEntityImpl getImportStatus() {
        return (IPMSEntityImpl)getEntity(1);
    }


    /**
     * Gets the attribute value for IMPORT_ID using the alias name ImportId.
     * @return the IMPORT_ID
     */
    public String getImportId() {
        return (String) getAttributeInternal(IMPORTID);
    }

    /**
     * Sets <code>value</code> as attribute value for IMPORT_ID using the alias name ImportId.
     * @param value value to set the IMPORT_ID
     */
    public void setImportId(String value) {
        setAttributeInternal(IMPORTID, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public String getProjectId() {
        return (String) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(String value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for STUDY_ID using the alias name StudyId.
     * @return the STUDY_ID
     */
    public String getStudyId() {
        return (String) getAttributeInternal(STUDYID);
    }

    /**
     * Sets <code>value</code> as attribute value for STUDY_ID using the alias name StudyId.
     * @param value value to set the STUDY_ID
     */
    public void setStudyId(String value) {
        setAttributeInternal(STUDYID, value);
    }

    /**
     * Gets the attribute value for WBS_ID using the alias name WbsId.
     * @return the WBS_ID
     */
    public String getWbsId() {
        return (String) getAttributeInternal(WBSID);
    }

    /**
     * Sets <code>value</code> as attribute value for WBS_ID using the alias name WbsId.
     * @param value value to set the WBS_ID
     */
    public void setWbsId(String value) {
        setAttributeInternal(WBSID, value);
    }

    /**
     * Gets the attribute value for NAME using the alias name Name.
     * @return the NAME
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME using the alias name Name.
     * @param value value to set the NAME
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for FINISH_DATE using the alias name FinishDate.
     * @return the FINISH_DATE
     */
    public Date getFinishDate() {
        return (Date) getAttributeInternal(FINISHDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for FINISH_DATE using the alias name FinishDate.
     * @param value value to set the FINISH_DATE
     */
    public void setFinishDate(Date value) {
        setAttributeInternal(FINISHDATE, value);
    }

    /**
     * Gets the attribute value for PLACEHOLDER using the alias name Placeholder.
     * @return the PLACEHOLDER
     */
    public BigDecimal getPlaceholder() {
        return (BigDecimal) getAttributeInternal(PLACEHOLDER);
    }

    /**
     * Sets <code>value</code> as attribute value for PLACEHOLDER using the alias name Placeholder.
     * @param value value to set the PLACEHOLDER
     */
    public void setPlaceholder(BigDecimal value) {
        setAttributeInternal(PLACEHOLDER, value);
    }

    /**
     * Gets the attribute value for STATUS_CODE using the alias name StatusCode.
     * @return the STATUS_CODE
     */
    public String getStatusCode() {
        return (String) getAttributeInternal(STATUSCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS_CODE using the alias name StatusCode.
     * @param value value to set the STATUS_CODE
     */
    public void setStatusCode(String value) {
        setAttributeInternal(STATUSCODE, value);
    }

    /**
     * Gets the attribute value for STATUS_DESCRIPTION using the alias name StatusDescription.
     * @return the STATUS_DESCRIPTION
     */
    public String getStatusDescription() {
        return (String) getAttributeInternal(STATUSDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS_DESCRIPTION using the alias name StatusDescription.
     * @param value value to set the STATUS_DESCRIPTION
     */
    public void setStatusDescription(String value) {
        setAttributeInternal(STATUSDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for CREATE_DATE using the alias name CreateDate.
     * @return the CREATE_DATE
     */
    public Date getCreateDate() {
        return (Date) getAttributeInternal(CREATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_DATE using the alias name CreateDate.
     * @param value value to set the CREATE_DATE
     */
    public void setCreateDate(Date value) {
        setAttributeInternal(CREATEDATE, value);
    }

    /**
     * Gets the attribute value for NAME using the alias name StatusName.
     * @return the NAME
     */
    public String getStatusName() {
        return (String) getAttributeInternal(STATUSNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME using the alias name StatusName.
     * @param value value to set the NAME
     */
    public void setStatusName(String value) {
        setAttributeInternal(STATUSNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ActionName.
     * @return the ActionName
     */
    public String getActionName() {
        return (String) getAttributeInternal(ACTIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActionName.
     * @param value value to set the  ActionName
     */
    public void setActionName(String value) {
        setAttributeInternal(ACTIONNAME, value);
    }

    /**
     * Gets the attribute value for ACTION_CODE using the alias name ActionCode.
     * @return the ACTION_CODE
     */
    public String getActionCode() {
        return (String) getAttributeInternal(ACTIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTION_CODE using the alias name ActionCode.
     * @param value value to set the ACTION_CODE
     */
    public void setActionCode(String value) {
        setAttributeInternal(ACTIONCODE, value);
    }

    /**
     * Gets the attribute value for CODE using the alias name Code.
     * @return the CODE
     */
    public String getCode() {
        return (String) getAttributeInternal(CODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CODE using the alias name Code.
     * @param value value to set the CODE
     */
    public void setCode(String value) {
        setAttributeInternal(CODE, value);
    }

    /**
     * Gets the attribute value for OLD_FINISH_DATE using the alias name OldFinishDate.
     * @return the OLD_FINISH_DATE
     */
    public Date getOldFinishDate() {
        return (Date) getAttributeInternal(OLDFINISHDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OLD_FINISH_DATE using the alias name OldFinishDate.
     * @param value value to set the OLD_FINISH_DATE
     */
    public void setOldFinishDate(Date value) {
        setAttributeInternal(OLDFINISHDATE, value);
    }

    /**
     * Gets the attribute value for OLD_START_DATE using the alias name OldStartDate.
     * @return the OLD_START_DATE
     */
    public Date getOldStartDate() {
        return (Date) getAttributeInternal(OLDSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OLD_START_DATE using the alias name OldStartDate.
     * @param value value to set the OLD_START_DATE
     */
    public void setOldStartDate(Date value) {
        setAttributeInternal(OLDSTARTDATE, value);
    }


    /**
     * Gets the attribute value for IS_EXISTING using the alias name IsExisting.
     * @return the IS_EXISTING
     */
    public Boolean getIsExisting() {
        return (Boolean) getAttributeInternal(ISEXISTING);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_EXISTING using the alias name IsExisting.
     * @param value value to set the IS_EXISTING
     */
    public void setIsExisting(Boolean value) {
        setAttributeInternal(ISEXISTING, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ImportActionView.
     */
    public RowIterator getImportActionView() {
        return (RowIterator)getAttributeInternal(IMPORTACTIONVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ImportStatusView.
     */
    public RowIterator getImportStatusView() {
        return (RowIterator)getAttributeInternal(IMPORTSTATUSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ImportActionView1.
     */
    public RowSet getImportActionView1() {
        return (RowSet)getAttributeInternal(IMPORTACTIONVIEW1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
