package com.bayer.ipms.model.views.common;

import java.sql.Date;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 26 10:53:22 CET 2021
// ---------------------------------------------------------------------
public interface CollaborationDetailsViewRow extends Row {
    void refresh();


    String getComment();

    Date getCreateDate();

    String getCreateUserId();

    String getEndPhase();

    Integer getId();


    String getProjectId();


    Date getUpdateDate();

    String getUpdateUserId();


    void setComment(String value);

    void setEndPhase(String value);


    void setProjectId(String value);


    RowSet getCollaborationTypeView();

    RowSet getPartnerView();
}

