package com.bayer.ipms.model.views.common;

import java.util.Map;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 13 15:44:47 EEST 2014
// ---------------------------------------------------------------------
public interface CostsProbabilityDefaultView extends ViewObject {
    Map<String, CostsProbabilityDefaultViewRow> getInternal();
}
