package com.bayer.ipms.model.views.common;

import oracle.jbo.RowSet;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 13 11:39:13 EEST 2013
// ---------------------------------------------------------------------
public interface CostsProbabilityInternalViewRow extends CostsProbabilityViewRow {
    String getPhaseName();


    void setProbability(Integer value);

    String getPhaseCode();

    RowSet getCostsProbabilityDefaultView();

    CostsProbabilitySpecificViewRow getDefault();
}
