package com.bayer.ipms.model.views.common;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 23 18:47:02 EEST 2014
// ---------------------------------------------------------------------
public interface CostsProbabilitySpecificViewRow extends CostsProbabilityViewRow {
    String getPhaseCode();
}
