package com.bayer.ipms.model.views.common;

import java.sql.Date;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 14 16:10:30 EEST 2015
// ---------------------------------------------------------------------
public interface DiscrepancyDetailsView extends ViewObject {
    void setSearchStudyIdVar(String value);

    void setSearchStudyModusVar(String value);

    void setSearchClinicalPlanTypeVar(String value);


    void setSearchFpfvDateFromVar(Date value);

    void setSearchFpfvDateToVar(Date value);

}

