package com.bayer.ipms.model.views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 26 09:14:28 EEST 2015
// ---------------------------------------------------------------------
public interface GoalStatusViewRow extends Row {
    void refresh();

    String getCode();

    Integer getIsActive();

    String getName();
}

