package com.bayer.ipms.model.views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 24 11:53:43 EEST 2016
// ---------------------------------------------------------------------
public interface HelpBundleViewRow extends Row {
    String getCode();

    String getDefinition();

    String getUrl();
}

