package com.bayer.ipms.model.views.common;

import java.sql.Clob;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 19 15:18:42 EEST 2015
// ---------------------------------------------------------------------
public interface LtcInstanceViewRow extends Row {

    void refresh();

    void launch();

    void submit();

    void recalculateTotals();

    void prefill();

    Clob getExcelReport();

    String getStatusCode();

    String getIsReportGenerated();

    void setStageNumber(Integer value);

    void setStatusCode(String value);

    void prefillProfit();

    String getProjectId();
}

