package com.bayer.ipms.model.views.common;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 10 18:26:26 EEST 2014
// ---------------------------------------------------------------------
public interface NewsViewRow extends Row {
    RowSet getNewsCategoryView();
}
