package com.bayer.ipms.model.views.common;

import oracle.jbo.ViewObject;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 27 21:11:32 EEST 2015
// ---------------------------------------------------------------------
public interface ProgramGoalsView extends ViewObject {
    void afterRollback(TransactionEvent TransactionEvent);

    void applyCriteria(String criteria);

    void beforeRollback(TransactionEvent TransactionEvent);

    void removeCriteria(String criteria);
}

