package com.bayer.ipms.model.views.common;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 04 10:46:20 EEST 2019
// ---------------------------------------------------------------------
public interface ProgramTopSubCategoryViewRow extends Row {
    Boolean getIsActive();

    void setIsActive(Boolean value);

    RowIterator getProgramTopValues();
}

