package com.bayer.ipms.model.views.common;

import java.sql.Date;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 16 12:50:09 EEST 2013
// ---------------------------------------------------------------------
public interface ProgramView extends ViewObject {
    void applyCriteria(String criteria);


    void setAllowedAssignedProjectTypes(String value);

    void setAllowedProjectTypes(String value);


    void setSearchAreaCodeVar(String value);


    void setProgramCode(String value);

    String createProgram(String code, String name);

    void send(String id, String callback, String action);

    String getSearchAreaCodeVar();

    Boolean getSearchIsHprVar();

    Boolean getSearchIsPortfolioVar();

    String getSearchProjectCodeVar();

    String getSearchProjectNameVar();

    String getSearchSbeCodeVar();

    String getSearchStatusVar();

    void setSearchIsHprVar(Boolean value);

    void setSearchIsPortfolioVar(Boolean value);

    void setSearchProjectCodeVar(String value);

    void setSearchProjectNameVar(String value);

    void setSearchSbeCodeVar(String value);

    void setSearchStatusVar(String value);


    void setSearchVcName(String value);

    String getSearchStatusMnt();

    void setSearchProjectBUCodeVar(String value);


    Date getSearchProjectPocDateFromVar();

    Date getSearchProjectPocDateToVar();

    String getSearchProjectDevPhaseVar();

    void setSearchProjectDevPhaseVar(String value);

    void setCurrentLeTagIdVar(String value);

    String getSearchProjectStateMntVar();

    String getSearchProjectStateVar();

    void setCurrentLtcTagIdVar(String value);

    void setSearchProjectTaCodeVar(String value);

    void setSearchStudyCodeVar(String value);


    void initMaintainGoals(String programId, Integer programGoalsId, String projectId);
}
