package com.bayer.ipms.model.views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 25 15:38:14 CET 2022
// ---------------------------------------------------------------------
public interface ProjectRelatedMspViewRow extends Row {


    String getProjectId();
    
    void setProjectId(String value);
    
    String getRelMspProjectId();

    void setRelMspProjectId(String value);

}

