package com.bayer.ipms.model.views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 13 11:14:51 CET 2022
// ---------------------------------------------------------------------
public interface ProjectRelatedDevViewRow extends Row {

    String getProjectId();

    void setProjectId(String value);

    String getDevProjectId();

    void setDevProjectId(String value);
}

