package com.bayer.ipms.model.views.common;

import java.sql.Date;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 20 10:11:24 CEST 2021
// ---------------------------------------------------------------------
public interface RoadmapViewRow extends Row {
    void refresh();

    Date getDate();

    String getDescription();

    Integer getId();

    String getProjectId();

    String getTopic();

    void setDate(Date value);

    void setDescription(String value);

    void setProjectId(String value);

    void setTopic(String value);
    
    void createRoadmap(String projectId, Date date, String topic,  String description);

    Date getCreateDate();

    String getCreateUserId();

    Date getUpdateDate();

    String getUpdateUserId();

    void setCreateDate(Date value);

    void setCreateUserId(String value);

    void setUpdateDate(Date value);

    void setUpdateUserId(String value);
}

