package com.bayer.ipms.model.views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 24 15:59:04 EEST 2015
// ---------------------------------------------------------------------
public interface SubstanceCodeAssignmentViewRow extends Row {
    String getProjectId();

    String getSubstanceCode();

    void setProjectId(String value);

    void setSubstanceCode(String value);
}

