package com.bayer.ipms.model.views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 14 19:10:41 EEST 2016
// ---------------------------------------------------------------------
public interface TimelinePublishCommentsViewRow
  extends Row
{
  String getComments();
}

