package com.bayer.ipms.model.views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 09 12:37:19 EEST 2015
// ---------------------------------------------------------------------
public interface TppSubcategoryViewRow extends Row {
    void setIsActive(Boolean value);
}

