package com.bayer.ipms.model.views.lookups;

import com.bayer.ipms.model.base.IPMSViewObjectImpl;
import com.bayer.ipms.model.views.lookups.common.ProjectGoalFactorView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 16 10:56:43 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProjectGoalFactorViewImpl extends IPMSViewObjectImpl implements ProjectGoalFactorView {
    /**
     * This is the default constructor (do not remove).
     */
    public ProjectGoalFactorViewImpl() {
    }


    /**
     * Returns the bind variable value for SearchGFactorVal.
     * @return bind variable value for SearchGFactorVal
     */
    public Boolean getSearchGFactorVal() {
        return (Boolean) getNamedWhereClauseParam("SearchGFactorVal");
    }

    /**
     * Sets <code>value</code> for bind variable SearchGFactorVal.
     * @param value value to bind as SearchGFactorVal
     */
    public void setSearchGFactorVal(Boolean value) {
        setNamedWhereClauseParam("SearchGFactorVal", value);
    }
}

