package com.bayer.ipms.model.views.lookups;

import com.bayer.ipms.model.base.IPMSViewObjectImpl;
import com.bayer.ipms.model.views.lookups.common.ProjectGoalTargetYearView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 29 15:24:53 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProjectGoalTargetYearViewImpl extends IPMSViewObjectImpl implements ProjectGoalTargetYearView {
    /**
     * This is the default constructor (do not remove).
     */
    public ProjectGoalTargetYearViewImpl() {
    }
}

